package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryNoteReceive generated by hbm2java
 */
@Entity
@Table(name="DeliveryNoteReceive"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class DeliveryNoteReceive  implements java.io.Serializable {


     private String deliveryNoteReceiveId;
     private String deliveryNoteDetailId;
     private String deliveryNoteId;
     private String warehouseId;
     private String materialSerialNumber;
     private String parentSerialNumber;
     private Date receiveDate;
     private Integer receiveBy;
     private String idCondition;
     private String idStatus;
     private Integer createdBy;
     private Date createdDate;

    public DeliveryNoteReceive() {
    }

	
    public DeliveryNoteReceive(String deliveryNoteReceiveId, String deliveryNoteDetailId, String deliveryNoteId, String warehouseId, String materialSerialNumber) {
        this.deliveryNoteReceiveId = deliveryNoteReceiveId;
        this.deliveryNoteDetailId = deliveryNoteDetailId;
        this.deliveryNoteId = deliveryNoteId;
        this.warehouseId = warehouseId;
        this.materialSerialNumber = materialSerialNumber;
    }
    public DeliveryNoteReceive(String deliveryNoteReceiveId, String deliveryNoteDetailId, String deliveryNoteId, String warehouseId, String materialSerialNumber, String parentSerialNumber, Date receiveDate, Integer receiveBy, String idCondition, String idStatus, Integer createdBy, Date createdDate) {
       this.deliveryNoteReceiveId = deliveryNoteReceiveId;
       this.deliveryNoteDetailId = deliveryNoteDetailId;
       this.deliveryNoteId = deliveryNoteId;
       this.warehouseId = warehouseId;
       this.materialSerialNumber = materialSerialNumber;
       this.parentSerialNumber = parentSerialNumber;
       this.receiveDate = receiveDate;
       this.receiveBy = receiveBy;
       this.idCondition = idCondition;
       this.idStatus = idStatus;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="DeliveryNoteReceiveId", unique=true, nullable=false, length=36)
    public String getDeliveryNoteReceiveId() {
        return this.deliveryNoteReceiveId;
    }
    
    public void setDeliveryNoteReceiveId(String deliveryNoteReceiveId) {
        this.deliveryNoteReceiveId = deliveryNoteReceiveId;
    }

    
    @Column(name="DeliveryNoteDetailId", nullable=false, length=36)
    public String getDeliveryNoteDetailId() {
        return this.deliveryNoteDetailId;
    }
    
    public void setDeliveryNoteDetailId(String deliveryNoteDetailId) {
        this.deliveryNoteDetailId = deliveryNoteDetailId;
    }

    
    @Column(name="DeliveryNoteId", nullable=false, length=30)
    public String getDeliveryNoteId() {
        return this.deliveryNoteId;
    }
    
    public void setDeliveryNoteId(String deliveryNoteId) {
        this.deliveryNoteId = deliveryNoteId;
    }

    
    @Column(name="WarehouseId", nullable=false, length=40)
    public String getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }

    
    @Column(name="MaterialSerialNumber", nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ReceiveDate", length=23)
    public Date getReceiveDate() {
        return this.receiveDate;
    }
    
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    
    @Column(name="ReceiveBy")
    public Integer getReceiveBy() {
        return this.receiveBy;
    }
    
    public void setReceiveBy(Integer receiveBy) {
        this.receiveBy = receiveBy;
    }

    
    @Column(name="IdCondition", length=40)
    public String getIdCondition() {
        return this.idCondition;
    }
    
    public void setIdCondition(String idCondition) {
        this.idCondition = idCondition;
    }

    
    @Column(name="IdStatus", length=40)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


