package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryOrderDetail generated by hbm2java
 */
@Entity
@Table(name="DeliveryOrderDetail"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class DeliveryOrderDetail  implements java.io.Serializable {


     private String deliveryOrderDetailId;
     private String deliveryOrderId;
     private String reallocationDetailId;
     private String reallocationId;
     private String deliveryNoteDetailId;
     private String deliveryNoteId;
     private String materialSerialNumber;
     private String parentSerialNumber;
     private Date eventDate;
     private String eventStatusId;
     private String planSlboqid;
     private String planCustPo;
     private String planRegionId;
     private String planAreaId;
     private String planSiteId;
     private String actualSlboqid;
     private String actualCustPo;
     private String actualRegionId;
     private String actualAreaId;
     private String actualSiteId;
     private String compId;
     private String contactId;
     private Integer createdBy;
     private Date createdDate;

    public DeliveryOrderDetail() {
    }

	
    public DeliveryOrderDetail(String deliveryOrderDetailId, String deliveryOrderId, String reallocationId, String materialSerialNumber, String planSlboqid, String actualSlboqid) {
        this.deliveryOrderDetailId = deliveryOrderDetailId;
        this.deliveryOrderId = deliveryOrderId;
        this.reallocationId = reallocationId;
        this.materialSerialNumber = materialSerialNumber;
        this.planSlboqid = planSlboqid;
        this.actualSlboqid = actualSlboqid;
    }
    public DeliveryOrderDetail(String deliveryOrderDetailId, String deliveryOrderId, String reallocationDetailId, String reallocationId, String deliveryNoteDetailId, String deliveryNoteId, String materialSerialNumber, String parentSerialNumber, Date eventDate, String eventStatusId, String planSlboqid, String planCustPo, String planRegionId, String planAreaId, String planSiteId, String actualSlboqid, String actualCustPo, String actualRegionId, String actualAreaId, String actualSiteId, String compId, String contactId, Integer createdBy, Date createdDate) {
       this.deliveryOrderDetailId = deliveryOrderDetailId;
       this.deliveryOrderId = deliveryOrderId;
       this.reallocationDetailId = reallocationDetailId;
       this.reallocationId = reallocationId;
       this.deliveryNoteDetailId = deliveryNoteDetailId;
       this.deliveryNoteId = deliveryNoteId;
       this.materialSerialNumber = materialSerialNumber;
       this.parentSerialNumber = parentSerialNumber;
       this.eventDate = eventDate;
       this.eventStatusId = eventStatusId;
       this.planSlboqid = planSlboqid;
       this.planCustPo = planCustPo;
       this.planRegionId = planRegionId;
       this.planAreaId = planAreaId;
       this.planSiteId = planSiteId;
       this.actualSlboqid = actualSlboqid;
       this.actualCustPo = actualCustPo;
       this.actualRegionId = actualRegionId;
       this.actualAreaId = actualAreaId;
       this.actualSiteId = actualSiteId;
       this.compId = compId;
       this.contactId = contactId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="DeliveryOrderDetailId", unique=true, nullable=false, length=36)
    public String getDeliveryOrderDetailId() {
        return this.deliveryOrderDetailId;
    }
    
    public void setDeliveryOrderDetailId(String deliveryOrderDetailId) {
        this.deliveryOrderDetailId = deliveryOrderDetailId;
    }

    
    @Column(name="DeliveryOrderId", nullable=false, length=30)
    public String getDeliveryOrderId() {
        return this.deliveryOrderId;
    }
    
    public void setDeliveryOrderId(String deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId;
    }

    
    @Column(name="ReallocationDetailId", length=36)
    public String getReallocationDetailId() {
        return this.reallocationDetailId;
    }
    
    public void setReallocationDetailId(String reallocationDetailId) {
        this.reallocationDetailId = reallocationDetailId;
    }

    
    @Column(name="ReallocationId", nullable=false, length=30)
    public String getReallocationId() {
        return this.reallocationId;
    }
    
    public void setReallocationId(String reallocationId) {
        this.reallocationId = reallocationId;
    }

    
    @Column(name="DeliveryNoteDetailId", length=36)
    public String getDeliveryNoteDetailId() {
        return this.deliveryNoteDetailId;
    }
    
    public void setDeliveryNoteDetailId(String deliveryNoteDetailId) {
        this.deliveryNoteDetailId = deliveryNoteDetailId;
    }

    
    @Column(name="DeliveryNoteId", length=30)
    public String getDeliveryNoteId() {
        return this.deliveryNoteId;
    }
    
    public void setDeliveryNoteId(String deliveryNoteId) {
        this.deliveryNoteId = deliveryNoteId;
    }

    
    @Column(name="MaterialSerialNumber", nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EventDate", length=23)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    
    @Column(name="EventStatusId", length=40)
    public String getEventStatusId() {
        return this.eventStatusId;
    }
    
    public void setEventStatusId(String eventStatusId) {
        this.eventStatusId = eventStatusId;
    }

    
    @Column(name="PlanSLBOQId", nullable=false, length=36)
    public String getPlanSlboqid() {
        return this.planSlboqid;
    }
    
    public void setPlanSlboqid(String planSlboqid) {
        this.planSlboqid = planSlboqid;
    }

    
    @Column(name="PlanCustPo", length=100)
    public String getPlanCustPo() {
        return this.planCustPo;
    }
    
    public void setPlanCustPo(String planCustPo) {
        this.planCustPo = planCustPo;
    }

    
    @Column(name="PlanRegionId", length=40)
    public String getPlanRegionId() {
        return this.planRegionId;
    }
    
    public void setPlanRegionId(String planRegionId) {
        this.planRegionId = planRegionId;
    }

    
    @Column(name="PlanAreaId", length=40)
    public String getPlanAreaId() {
        return this.planAreaId;
    }
    
    public void setPlanAreaId(String planAreaId) {
        this.planAreaId = planAreaId;
    }

    
    @Column(name="PlanSiteId", length=40)
    public String getPlanSiteId() {
        return this.planSiteId;
    }
    
    public void setPlanSiteId(String planSiteId) {
        this.planSiteId = planSiteId;
    }

    
    @Column(name="ActualSLBOQId", nullable=false, length=36)
    public String getActualSlboqid() {
        return this.actualSlboqid;
    }
    
    public void setActualSlboqid(String actualSlboqid) {
        this.actualSlboqid = actualSlboqid;
    }

    
    @Column(name="ActualCustPo", length=100)
    public String getActualCustPo() {
        return this.actualCustPo;
    }
    
    public void setActualCustPo(String actualCustPo) {
        this.actualCustPo = actualCustPo;
    }

    
    @Column(name="ActualRegionId", length=40)
    public String getActualRegionId() {
        return this.actualRegionId;
    }
    
    public void setActualRegionId(String actualRegionId) {
        this.actualRegionId = actualRegionId;
    }

    
    @Column(name="ActualAreaId", length=40)
    public String getActualAreaId() {
        return this.actualAreaId;
    }
    
    public void setActualAreaId(String actualAreaId) {
        this.actualAreaId = actualAreaId;
    }

    
    @Column(name="ActualSiteId", length=40)
    public String getActualSiteId() {
        return this.actualSiteId;
    }
    
    public void setActualSiteId(String actualSiteId) {
        this.actualSiteId = actualSiteId;
    }

    
    @Column(name="CompId", length=40)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    
    @Column(name="ContactId", length=40)
    public String getContactId() {
        return this.contactId;
    }
    
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


