package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoDeliveryNote generated by hbm2java
 */
@Entity
@Table(name="LoDeliveryNote"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LoDeliveryNote  implements java.io.Serializable {


     private String loDeliveryNoteId;
     private LoMaterialGroup loMaterialGroup;
     private LoMaterialType loMaterialType;
     private TransactionHeader transactionHeader;
     private String materialSerialNumber;
     private Boolean isExists;
     private String createdBy;
     private Date createdDate;

    public LoDeliveryNote() {
    }

	
    public LoDeliveryNote(String loDeliveryNoteId, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, TransactionHeader transactionHeader) {
        this.loDeliveryNoteId = loDeliveryNoteId;
        this.loMaterialGroup = loMaterialGroup;
        this.loMaterialType = loMaterialType;
        this.transactionHeader = transactionHeader;
    }
    public LoDeliveryNote(String loDeliveryNoteId, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, TransactionHeader transactionHeader, String materialSerialNumber, Boolean isExists, String createdBy, Date createdDate) {
       this.loDeliveryNoteId = loDeliveryNoteId;
       this.loMaterialGroup = loMaterialGroup;
       this.loMaterialType = loMaterialType;
       this.transactionHeader = transactionHeader;
       this.materialSerialNumber = materialSerialNumber;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="LoDeliveryNoteId", unique=true, nullable=false, length=40)
    public String getLoDeliveryNoteId() {
        return this.loDeliveryNoteId;
    }
    
    public void setLoDeliveryNoteId(String loDeliveryNoteId) {
        this.loDeliveryNoteId = loDeliveryNoteId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialGroupId", nullable=false)
    public LoMaterialGroup getLoMaterialGroup() {
        return this.loMaterialGroup;
    }
    
    public void setLoMaterialGroup(LoMaterialGroup loMaterialGroup) {
        this.loMaterialGroup = loMaterialGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialTypeId", nullable=false)
    public LoMaterialType getLoMaterialType() {
        return this.loMaterialType;
    }
    
    public void setLoMaterialType(LoMaterialType loMaterialType) {
        this.loMaterialType = loMaterialType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MainFormId", nullable=false)
    public TransactionHeader getTransactionHeader() {
        return this.transactionHeader;
    }
    
    public void setTransactionHeader(TransactionHeader transactionHeader) {
        this.transactionHeader = transactionHeader;
    }

    
    @Column(name="MaterialSerialNumber", length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


