package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoDeliveryRequestSiteId generated by hbm2java
 */
@Entity
@Table(name="LoDeliveryRequestSiteId"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LoDeliveryRequestSiteId  implements java.io.Serializable {


     private String loDeliveryRequestSiteId;
     private TransactionHeader transactionHeader;
     private String fromSlboqid;
     private String toSlboqid;
     private Integer stepCount;
     private Boolean isExists;

    public LoDeliveryRequestSiteId() {
    }

	
    public LoDeliveryRequestSiteId(String loDeliveryRequestSiteId) {
        this.loDeliveryRequestSiteId = loDeliveryRequestSiteId;
    }
    public LoDeliveryRequestSiteId(String loDeliveryRequestSiteId, TransactionHeader transactionHeader, String fromSlboqid, String toSlboqid, Integer stepCount, Boolean isExists) {
       this.loDeliveryRequestSiteId = loDeliveryRequestSiteId;
       this.transactionHeader = transactionHeader;
       this.fromSlboqid = fromSlboqid;
       this.toSlboqid = toSlboqid;
       this.stepCount = stepCount;
       this.isExists = isExists;
    }
   
     @Id 

    
    @Column(name="LoDeliveryRequestSiteId", unique=true, nullable=false, length=40)
    public String getLoDeliveryRequestSiteId() {
        return this.loDeliveryRequestSiteId;
    }
    
    public void setLoDeliveryRequestSiteId(String loDeliveryRequestSiteId) {
        this.loDeliveryRequestSiteId = loDeliveryRequestSiteId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MainFormId")
    public TransactionHeader getTransactionHeader() {
        return this.transactionHeader;
    }
    
    public void setTransactionHeader(TransactionHeader transactionHeader) {
        this.transactionHeader = transactionHeader;
    }

    
    @Column(name="FromSLBOQId", length=36)
    public String getFromSlboqid() {
        return this.fromSlboqid;
    }
    
    public void setFromSlboqid(String fromSlboqid) {
        this.fromSlboqid = fromSlboqid;
    }

    
    @Column(name="ToSLBOQId", length=36)
    public String getToSlboqid() {
        return this.toSlboqid;
    }
    
    public void setToSlboqid(String toSlboqid) {
        this.toSlboqid = toSlboqid;
    }

    
    @Column(name="StepCount")
    public Integer getStepCount() {
        return this.stepCount;
    }
    
    public void setStepCount(Integer stepCount) {
        this.stepCount = stepCount;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }




}


