package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogInbound generated by hbm2java
 */
@Entity
@Table(name="LogInbound"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LogInbound  implements java.io.Serializable {


     private String materialSerialNumber;
     private LogMaterialGroup logMaterialGroup;
     private LogMaterialType logMaterialType;
     private LogSupplier logSupplier;
     private LogWarehouse logWarehouse;
     private String parentSerialNumber;
     private String idComplation;
     private String idCondition;
     private String idStatus;
     private String productId;
     private Date suppWarrantyStart;
     private Date suppWarrantyEnd;
     private Date recievedDate;
     private Integer recieveBy;
     private String supplierPoNumber;
     private String goodRecievedNo;
     private String iscalaDeliveryNote;
     private Boolean isReservation;
     private Boolean isReceived;
     private Integer createdBy;
     private Date createdDate;
     private Set logMaterialTaggingDetails = new HashSet(0);

    public LogInbound() {
    }

	
    public LogInbound(String materialSerialNumber, LogMaterialGroup logMaterialGroup, LogMaterialType logMaterialType, LogSupplier logSupplier, LogWarehouse logWarehouse) {
        this.materialSerialNumber = materialSerialNumber;
        this.logMaterialGroup = logMaterialGroup;
        this.logMaterialType = logMaterialType;
        this.logSupplier = logSupplier;
        this.logWarehouse = logWarehouse;
    }
    public LogInbound(String materialSerialNumber, LogMaterialGroup logMaterialGroup, LogMaterialType logMaterialType, LogSupplier logSupplier, LogWarehouse logWarehouse, String parentSerialNumber, String idComplation, String idCondition, String idStatus, String productId, Date suppWarrantyStart, Date suppWarrantyEnd, Date recievedDate, Integer recieveBy, String supplierPoNumber, String goodRecievedNo, String iscalaDeliveryNote, Boolean isReservation, Boolean isReceived, Integer createdBy, Date createdDate, Set logMaterialTaggingDetails) {
       this.materialSerialNumber = materialSerialNumber;
       this.logMaterialGroup = logMaterialGroup;
       this.logMaterialType = logMaterialType;
       this.logSupplier = logSupplier;
       this.logWarehouse = logWarehouse;
       this.parentSerialNumber = parentSerialNumber;
       this.idComplation = idComplation;
       this.idCondition = idCondition;
       this.idStatus = idStatus;
       this.productId = productId;
       this.suppWarrantyStart = suppWarrantyStart;
       this.suppWarrantyEnd = suppWarrantyEnd;
       this.recievedDate = recievedDate;
       this.recieveBy = recieveBy;
       this.supplierPoNumber = supplierPoNumber;
       this.goodRecievedNo = goodRecievedNo;
       this.iscalaDeliveryNote = iscalaDeliveryNote;
       this.isReservation = isReservation;
       this.isReceived = isReceived;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.logMaterialTaggingDetails = logMaterialTaggingDetails;
    }
   
     @Id 

    
    @Column(name="MaterialSerialNumber", unique=true, nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LogMaterialGroupId", nullable=false)
    public LogMaterialGroup getLogMaterialGroup() {
        return this.logMaterialGroup;
    }
    
    public void setLogMaterialGroup(LogMaterialGroup logMaterialGroup) {
        this.logMaterialGroup = logMaterialGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LogMaterialTypeId", nullable=false)
    public LogMaterialType getLogMaterialType() {
        return this.logMaterialType;
    }
    
    public void setLogMaterialType(LogMaterialType logMaterialType) {
        this.logMaterialType = logMaterialType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LogSupplierId", nullable=false)
    public LogSupplier getLogSupplier() {
        return this.logSupplier;
    }
    
    public void setLogSupplier(LogSupplier logSupplier) {
        this.logSupplier = logSupplier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LogWarehouseId", nullable=false)
    public LogWarehouse getLogWarehouse() {
        return this.logWarehouse;
    }
    
    public void setLogWarehouse(LogWarehouse logWarehouse) {
        this.logWarehouse = logWarehouse;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    
    @Column(name="IdComplation", length=40)
    public String getIdComplation() {
        return this.idComplation;
    }
    
    public void setIdComplation(String idComplation) {
        this.idComplation = idComplation;
    }

    
    @Column(name="IdCondition", length=40)
    public String getIdCondition() {
        return this.idCondition;
    }
    
    public void setIdCondition(String idCondition) {
        this.idCondition = idCondition;
    }

    
    @Column(name="IdStatus", length=40)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SuppWarrantyStart", length=23)
    public Date getSuppWarrantyStart() {
        return this.suppWarrantyStart;
    }
    
    public void setSuppWarrantyStart(Date suppWarrantyStart) {
        this.suppWarrantyStart = suppWarrantyStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SuppWarrantyEnd", length=23)
    public Date getSuppWarrantyEnd() {
        return this.suppWarrantyEnd;
    }
    
    public void setSuppWarrantyEnd(Date suppWarrantyEnd) {
        this.suppWarrantyEnd = suppWarrantyEnd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RecievedDate", length=23)
    public Date getRecievedDate() {
        return this.recievedDate;
    }
    
    public void setRecievedDate(Date recievedDate) {
        this.recievedDate = recievedDate;
    }

    
    @Column(name="RecieveBy")
    public Integer getRecieveBy() {
        return this.recieveBy;
    }
    
    public void setRecieveBy(Integer recieveBy) {
        this.recieveBy = recieveBy;
    }

    
    @Column(name="SupplierPoNumber", length=40)
    public String getSupplierPoNumber() {
        return this.supplierPoNumber;
    }
    
    public void setSupplierPoNumber(String supplierPoNumber) {
        this.supplierPoNumber = supplierPoNumber;
    }

    
    @Column(name="GoodRecievedNo", length=100)
    public String getGoodRecievedNo() {
        return this.goodRecievedNo;
    }
    
    public void setGoodRecievedNo(String goodRecievedNo) {
        this.goodRecievedNo = goodRecievedNo;
    }

    
    @Column(name="iScalaDeliveryNote", length=100)
    public String getIscalaDeliveryNote() {
        return this.iscalaDeliveryNote;
    }
    
    public void setIscalaDeliveryNote(String iscalaDeliveryNote) {
        this.iscalaDeliveryNote = iscalaDeliveryNote;
    }

    
    @Column(name="IsReservation")
    public Boolean getIsReservation() {
        return this.isReservation;
    }
    
    public void setIsReservation(Boolean isReservation) {
        this.isReservation = isReservation;
    }

    
    @Column(name="IsReceived")
    public Boolean getIsReceived() {
        return this.isReceived;
    }
    
    public void setIsReceived(Boolean isReceived) {
        this.isReceived = isReceived;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logInbound")
    public Set getLogMaterialTaggingDetails() {
        return this.logMaterialTaggingDetails;
    }
    
    public void setLogMaterialTaggingDetails(Set logMaterialTaggingDetails) {
        this.logMaterialTaggingDetails = logMaterialTaggingDetails;
    }




}


