package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogMaterialCondition generated by hbm2java
 */
@Entity
@Table(name="LogMaterialCondition"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LogMaterialCondition  implements java.io.Serializable {


     private String logMaterialConditionId;
     private String logParentId;
     private String logParentSource;
     private String logDescription;
     private String materialSerialNumber;
     private String warehouseId;
     private String conditionId;
     private String statusId;
     private String complationId;
     private Boolean isLastUpdate;
     private Date lastUpdate;

    public LogMaterialCondition() {
    }

	
    public LogMaterialCondition(String logMaterialConditionId) {
        this.logMaterialConditionId = logMaterialConditionId;
    }
    public LogMaterialCondition(String logMaterialConditionId, String logParentId, String logParentSource, String logDescription, String materialSerialNumber, String warehouseId, String conditionId, String statusId, String complationId, Boolean isLastUpdate, Date lastUpdate) {
       this.logMaterialConditionId = logMaterialConditionId;
       this.logParentId = logParentId;
       this.logParentSource = logParentSource;
       this.logDescription = logDescription;
       this.materialSerialNumber = materialSerialNumber;
       this.warehouseId = warehouseId;
       this.conditionId = conditionId;
       this.statusId = statusId;
       this.complationId = complationId;
       this.isLastUpdate = isLastUpdate;
       this.lastUpdate = lastUpdate;
    }
   
     @Id 

    
    @Column(name="LogMaterialConditionId", unique=true, nullable=false, length=36)
    public String getLogMaterialConditionId() {
        return this.logMaterialConditionId;
    }
    
    public void setLogMaterialConditionId(String logMaterialConditionId) {
        this.logMaterialConditionId = logMaterialConditionId;
    }

    
    @Column(name="LogParentId", length=50)
    public String getLogParentId() {
        return this.logParentId;
    }
    
    public void setLogParentId(String logParentId) {
        this.logParentId = logParentId;
    }

    
    @Column(name="LogParentSource", length=50)
    public String getLogParentSource() {
        return this.logParentSource;
    }
    
    public void setLogParentSource(String logParentSource) {
        this.logParentSource = logParentSource;
    }

    
    @Column(name="LogDescription")
    public String getLogDescription() {
        return this.logDescription;
    }
    
    public void setLogDescription(String logDescription) {
        this.logDescription = logDescription;
    }

    
    @Column(name="MaterialSerialNumber", length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="WarehouseId", length=40)
    public String getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }

    
    @Column(name="ConditionId", length=40)
    public String getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }

    
    @Column(name="StatusId", length=40)
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="ComplationId", length=40)
    public String getComplationId() {
        return this.complationId;
    }
    
    public void setComplationId(String complationId) {
        this.complationId = complationId;
    }

    
    @Column(name="IsLastUpdate")
    public Boolean getIsLastUpdate() {
        return this.isLastUpdate;
    }
    
    public void setIsLastUpdate(Boolean isLastUpdate) {
        this.isLastUpdate = isLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdate", length=23)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


