package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogMaterialGroup generated by hbm2java
 */
@Entity
@Table(name="LogMaterialGroup"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LogMaterialGroup  implements java.io.Serializable {


     private String logMaterialGroupId;
     private LogSupplier logSupplier;
     private String productId;
     private String materialGroupName;
     private Boolean isExists;
     private Integer createdBy;
     private Date createdDate;
     private Set logMaterialTypes = new HashSet(0);
     private Set logInbounds = new HashSet(0);

    public LogMaterialGroup() {
    }

	
    public LogMaterialGroup(String logMaterialGroupId, LogSupplier logSupplier, String productId) {
        this.logMaterialGroupId = logMaterialGroupId;
        this.logSupplier = logSupplier;
        this.productId = productId;
    }
    public LogMaterialGroup(String logMaterialGroupId, LogSupplier logSupplier, String productId, String materialGroupName, Boolean isExists, Integer createdBy, Date createdDate, Set logMaterialTypes, Set logInbounds) {
       this.logMaterialGroupId = logMaterialGroupId;
       this.logSupplier = logSupplier;
       this.productId = productId;
       this.materialGroupName = materialGroupName;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.logMaterialTypes = logMaterialTypes;
       this.logInbounds = logInbounds;
    }
   
     @Id 

    
    @Column(name="LogMaterialGroupId", unique=true, nullable=false, length=40)
    public String getLogMaterialGroupId() {
        return this.logMaterialGroupId;
    }
    
    public void setLogMaterialGroupId(String logMaterialGroupId) {
        this.logMaterialGroupId = logMaterialGroupId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LogSupplierId", nullable=false)
    public LogSupplier getLogSupplier() {
        return this.logSupplier;
    }
    
    public void setLogSupplier(LogSupplier logSupplier) {
        this.logSupplier = logSupplier;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="MaterialGroupName", length=40)
    public String getMaterialGroupName() {
        return this.materialGroupName;
    }
    
    public void setMaterialGroupName(String materialGroupName) {
        this.materialGroupName = materialGroupName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logMaterialGroup")
    public Set getLogMaterialTypes() {
        return this.logMaterialTypes;
    }
    
    public void setLogMaterialTypes(Set logMaterialTypes) {
        this.logMaterialTypes = logMaterialTypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logMaterialGroup")
    public Set getLogInbounds() {
        return this.logInbounds;
    }
    
    public void setLogInbounds(Set logInbounds) {
        this.logInbounds = logInbounds;
    }




}


