package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogMaterialTaggingDetail generated by hbm2java
 */
@Entity
@Table(name="LogMaterialTaggingDetail"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LogMaterialTaggingDetail  implements java.io.Serializable {


     private String logMaterialTaggingDetailId;
     private LogInbound logInbound;
     private Slboq slboq;
     private String logTaggingId;
     private String refDocumentId;
     private String refDocumentType;
     private String parentSerialNumber;
     private Integer donorId;
     private Date tanggingDate;
     private String sourceRegionId;
     private String sourceAreaId;
     private String sourceSiteId;
     private String actualRegionId;
     private String actualAreaId;
     private String actualSiteId;
     private Boolean isExpired;
     private String taggingStatusId;
     private Integer createdBy;
     private Date createdDate;

    public LogMaterialTaggingDetail() {
    }

	
    public LogMaterialTaggingDetail(String logMaterialTaggingDetailId, LogInbound logInbound, Slboq slboq, String logTaggingId) {
        this.logMaterialTaggingDetailId = logMaterialTaggingDetailId;
        this.logInbound = logInbound;
        this.slboq = slboq;
        this.logTaggingId = logTaggingId;
    }
    public LogMaterialTaggingDetail(String logMaterialTaggingDetailId, LogInbound logInbound, Slboq slboq, String logTaggingId, String refDocumentId, String refDocumentType, String parentSerialNumber, Integer donorId, Date tanggingDate, String sourceRegionId, String sourceAreaId, String sourceSiteId, String actualRegionId, String actualAreaId, String actualSiteId, Boolean isExpired, String taggingStatusId, Integer createdBy, Date createdDate) {
       this.logMaterialTaggingDetailId = logMaterialTaggingDetailId;
       this.logInbound = logInbound;
       this.slboq = slboq;
       this.logTaggingId = logTaggingId;
       this.refDocumentId = refDocumentId;
       this.refDocumentType = refDocumentType;
       this.parentSerialNumber = parentSerialNumber;
       this.donorId = donorId;
       this.tanggingDate = tanggingDate;
       this.sourceRegionId = sourceRegionId;
       this.sourceAreaId = sourceAreaId;
       this.sourceSiteId = sourceSiteId;
       this.actualRegionId = actualRegionId;
       this.actualAreaId = actualAreaId;
       this.actualSiteId = actualSiteId;
       this.isExpired = isExpired;
       this.taggingStatusId = taggingStatusId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="LogMaterialTaggingDetailId", unique=true, nullable=false, length=36)
    public String getLogMaterialTaggingDetailId() {
        return this.logMaterialTaggingDetailId;
    }
    
    public void setLogMaterialTaggingDetailId(String logMaterialTaggingDetailId) {
        this.logMaterialTaggingDetailId = logMaterialTaggingDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialSerialNumber", nullable=false)
    public LogInbound getLogInbound() {
        return this.logInbound;
    }
    
    public void setLogInbound(LogInbound logInbound) {
        this.logInbound = logInbound;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SLBOQId", nullable=false)
    public Slboq getSlboq() {
        return this.slboq;
    }
    
    public void setSlboq(Slboq slboq) {
        this.slboq = slboq;
    }

    
    @Column(name="LogTaggingId", nullable=false, length=30)
    public String getLogTaggingId() {
        return this.logTaggingId;
    }
    
    public void setLogTaggingId(String logTaggingId) {
        this.logTaggingId = logTaggingId;
    }

    
    @Column(name="RefDocumentId", length=30)
    public String getRefDocumentId() {
        return this.refDocumentId;
    }
    
    public void setRefDocumentId(String refDocumentId) {
        this.refDocumentId = refDocumentId;
    }

    
    @Column(name="RefDocumentType", length=100)
    public String getRefDocumentType() {
        return this.refDocumentType;
    }
    
    public void setRefDocumentType(String refDocumentType) {
        this.refDocumentType = refDocumentType;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    
    @Column(name="DonorId")
    public Integer getDonorId() {
        return this.donorId;
    }
    
    public void setDonorId(Integer donorId) {
        this.donorId = donorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TanggingDate", length=23)
    public Date getTanggingDate() {
        return this.tanggingDate;
    }
    
    public void setTanggingDate(Date tanggingDate) {
        this.tanggingDate = tanggingDate;
    }

    
    @Column(name="SourceRegionId", length=40)
    public String getSourceRegionId() {
        return this.sourceRegionId;
    }
    
    public void setSourceRegionId(String sourceRegionId) {
        this.sourceRegionId = sourceRegionId;
    }

    
    @Column(name="SourceAreaId", length=40)
    public String getSourceAreaId() {
        return this.sourceAreaId;
    }
    
    public void setSourceAreaId(String sourceAreaId) {
        this.sourceAreaId = sourceAreaId;
    }

    
    @Column(name="SourceSiteId", length=40)
    public String getSourceSiteId() {
        return this.sourceSiteId;
    }
    
    public void setSourceSiteId(String sourceSiteId) {
        this.sourceSiteId = sourceSiteId;
    }

    
    @Column(name="ActualRegionId", length=40)
    public String getActualRegionId() {
        return this.actualRegionId;
    }
    
    public void setActualRegionId(String actualRegionId) {
        this.actualRegionId = actualRegionId;
    }

    
    @Column(name="ActualAreaId", length=40)
    public String getActualAreaId() {
        return this.actualAreaId;
    }
    
    public void setActualAreaId(String actualAreaId) {
        this.actualAreaId = actualAreaId;
    }

    
    @Column(name="ActualSiteId", length=40)
    public String getActualSiteId() {
        return this.actualSiteId;
    }
    
    public void setActualSiteId(String actualSiteId) {
        this.actualSiteId = actualSiteId;
    }

    
    @Column(name="IsExpired")
    public Boolean getIsExpired() {
        return this.isExpired;
    }
    
    public void setIsExpired(Boolean isExpired) {
        this.isExpired = isExpired;
    }

    
    @Column(name="TaggingStatusId", length=40)
    public String getTaggingStatusId() {
        return this.taggingStatusId;
    }
    
    public void setTaggingStatusId(String taggingStatusId) {
        this.taggingStatusId = taggingStatusId;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


