package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogWarehouse generated by hbm2java
 */
@Entity
@Table(name="LogWarehouse"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LogWarehouse  implements java.io.Serializable {


     private String logWarehouseId;
     private String productId;
     private String warehouseName;
     private String warehouseNameShort;
     private Boolean isExists;
     private Boolean isVirtual;
     private Boolean isDashboard;
     private Integer createdBy;
     private Date createdDate;
     private Set logInbounds = new HashSet(0);

    public LogWarehouse() {
    }

	
    public LogWarehouse(String logWarehouseId, String productId) {
        this.logWarehouseId = logWarehouseId;
        this.productId = productId;
    }
    public LogWarehouse(String logWarehouseId, String productId, String warehouseName, String warehouseNameShort, Boolean isExists, Boolean isVirtual, Boolean isDashboard, Integer createdBy, Date createdDate, Set logInbounds) {
       this.logWarehouseId = logWarehouseId;
       this.productId = productId;
       this.warehouseName = warehouseName;
       this.warehouseNameShort = warehouseNameShort;
       this.isExists = isExists;
       this.isVirtual = isVirtual;
       this.isDashboard = isDashboard;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.logInbounds = logInbounds;
    }
   
     @Id 

    
    @Column(name="LogWarehouseId", unique=true, nullable=false, length=40)
    public String getLogWarehouseId() {
        return this.logWarehouseId;
    }
    
    public void setLogWarehouseId(String logWarehouseId) {
        this.logWarehouseId = logWarehouseId;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="WarehouseName", length=100)
    public String getWarehouseName() {
        return this.warehouseName;
    }
    
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    
    @Column(name="WarehouseNameShort", length=100)
    public String getWarehouseNameShort() {
        return this.warehouseNameShort;
    }
    
    public void setWarehouseNameShort(String warehouseNameShort) {
        this.warehouseNameShort = warehouseNameShort;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="IsVirtual")
    public Boolean getIsVirtual() {
        return this.isVirtual;
    }
    
    public void setIsVirtual(Boolean isVirtual) {
        this.isVirtual = isVirtual;
    }

    
    @Column(name="IsDashboard")
    public Boolean getIsDashboard() {
        return this.isDashboard;
    }
    
    public void setIsDashboard(Boolean isDashboard) {
        this.isDashboard = isDashboard;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logWarehouse")
    public Set getLogInbounds() {
        return this.logInbounds;
    }
    
    public void setLogInbounds(Set logInbounds) {
        this.logInbounds = logInbounds;
    }




}


