package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoMaterialGroup generated by hbm2java
 */
@Entity
@Table(name="LoMaterialGroup"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LoMaterialGroup  implements java.io.Serializable {


     private String materialGroupId;
     private String productId;
     private String materialGroupName;
     private Boolean isExists;
     private String createdBy;
     private Date createdDate;
     private Set loDeliveryNotes = new HashSet(0);
     private Set loDeliveryRequests = new HashSet(0);
     private Set oldTransactionDetails = new HashSet(0);
     private Set loMaterialTypes = new HashSet(0);
     private Set loMaterialInbounds = new HashSet(0);

    public LoMaterialGroup() {
    }

	
    public LoMaterialGroup(String materialGroupId, String productId) {
        this.materialGroupId = materialGroupId;
        this.productId = productId;
    }
    public LoMaterialGroup(String materialGroupId, String productId, String materialGroupName, Boolean isExists, String createdBy, Date createdDate, Set loDeliveryNotes, Set loDeliveryRequests, Set oldTransactionDetails, Set loMaterialTypes, Set loMaterialInbounds) {
       this.materialGroupId = materialGroupId;
       this.productId = productId;
       this.materialGroupName = materialGroupName;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.loDeliveryNotes = loDeliveryNotes;
       this.loDeliveryRequests = loDeliveryRequests;
       this.oldTransactionDetails = oldTransactionDetails;
       this.loMaterialTypes = loMaterialTypes;
       this.loMaterialInbounds = loMaterialInbounds;
    }
   
     @Id 

    
    @Column(name="MaterialGroupId", unique=true, nullable=false, length=40)
    public String getMaterialGroupId() {
        return this.materialGroupId;
    }
    
    public void setMaterialGroupId(String materialGroupId) {
        this.materialGroupId = materialGroupId;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="MaterialGroupName", length=40)
    public String getMaterialGroupName() {
        return this.materialGroupName;
    }
    
    public void setMaterialGroupName(String materialGroupName) {
        this.materialGroupName = materialGroupName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialGroup")
    public Set getLoDeliveryNotes() {
        return this.loDeliveryNotes;
    }
    
    public void setLoDeliveryNotes(Set loDeliveryNotes) {
        this.loDeliveryNotes = loDeliveryNotes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialGroup")
    public Set getLoDeliveryRequests() {
        return this.loDeliveryRequests;
    }
    
    public void setLoDeliveryRequests(Set loDeliveryRequests) {
        this.loDeliveryRequests = loDeliveryRequests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialGroup")
    public Set getOldTransactionDetails() {
        return this.oldTransactionDetails;
    }
    
    public void setOldTransactionDetails(Set oldTransactionDetails) {
        this.oldTransactionDetails = oldTransactionDetails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialGroup")
    public Set getLoMaterialTypes() {
        return this.loMaterialTypes;
    }
    
    public void setLoMaterialTypes(Set loMaterialTypes) {
        this.loMaterialTypes = loMaterialTypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialGroup")
    public Set getLoMaterialInbounds() {
        return this.loMaterialInbounds;
    }
    
    public void setLoMaterialInbounds(Set loMaterialInbounds) {
        this.loMaterialInbounds = loMaterialInbounds;
    }




}


