package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoMaterialInbound generated by hbm2java
 */
@Entity
@Table(name="LoMaterialInbound"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LoMaterialInbound  implements java.io.Serializable {


     private String materialSerialNumber;
     private LoMaterialGroup loMaterialGroup;
     private LoMaterialType loMaterialType;
     private LoWarehouse loWarehouse;
     private SyCompany syCompany;
     private String embossedSerialNumber;
     private String complationId;
     private String conditionId;
     private String statusId;
     private String productId;
     private Date suppWarrantyStart;
     private Date suppWarrantyEnd;
     private Date recievedDate;
     private String recieveBy;
     private String supplierPoNumber;
     private String goodRecievedNo;
     private Boolean isReservation;
     private Boolean isReceived;
     private String createdBy;
     private Date createdDate;
     private Set loDeliveryOrders = new HashSet(0);

    public LoMaterialInbound() {
    }

	
    public LoMaterialInbound(String materialSerialNumber, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, LoWarehouse loWarehouse, String complationId, String conditionId, String statusId, String productId) {
        this.materialSerialNumber = materialSerialNumber;
        this.loMaterialGroup = loMaterialGroup;
        this.loMaterialType = loMaterialType;
        this.loWarehouse = loWarehouse;
        this.complationId = complationId;
        this.conditionId = conditionId;
        this.statusId = statusId;
        this.productId = productId;
    }
    public LoMaterialInbound(String materialSerialNumber, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, LoWarehouse loWarehouse, SyCompany syCompany, String embossedSerialNumber, String complationId, String conditionId, String statusId, String productId, Date suppWarrantyStart, Date suppWarrantyEnd, Date recievedDate, String recieveBy, String supplierPoNumber, String goodRecievedNo, Boolean isReservation, Boolean isReceived, String createdBy, Date createdDate, Set loDeliveryOrders) {
       this.materialSerialNumber = materialSerialNumber;
       this.loMaterialGroup = loMaterialGroup;
       this.loMaterialType = loMaterialType;
       this.loWarehouse = loWarehouse;
       this.syCompany = syCompany;
       this.embossedSerialNumber = embossedSerialNumber;
       this.complationId = complationId;
       this.conditionId = conditionId;
       this.statusId = statusId;
       this.productId = productId;
       this.suppWarrantyStart = suppWarrantyStart;
       this.suppWarrantyEnd = suppWarrantyEnd;
       this.recievedDate = recievedDate;
       this.recieveBy = recieveBy;
       this.supplierPoNumber = supplierPoNumber;
       this.goodRecievedNo = goodRecievedNo;
       this.isReservation = isReservation;
       this.isReceived = isReceived;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.loDeliveryOrders = loDeliveryOrders;
    }
   
     @Id 

    
    @Column(name="MaterialSerialNumber", unique=true, nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialGroupId", nullable=false)
    public LoMaterialGroup getLoMaterialGroup() {
        return this.loMaterialGroup;
    }
    
    public void setLoMaterialGroup(LoMaterialGroup loMaterialGroup) {
        this.loMaterialGroup = loMaterialGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialTypeId", nullable=false)
    public LoMaterialType getLoMaterialType() {
        return this.loMaterialType;
    }
    
    public void setLoMaterialType(LoMaterialType loMaterialType) {
        this.loMaterialType = loMaterialType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WarehouseId", nullable=false)
    public LoWarehouse getLoWarehouse() {
        return this.loWarehouse;
    }
    
    public void setLoWarehouse(LoWarehouse loWarehouse) {
        this.loWarehouse = loWarehouse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CompanyId")
    public SyCompany getSyCompany() {
        return this.syCompany;
    }
    
    public void setSyCompany(SyCompany syCompany) {
        this.syCompany = syCompany;
    }

    
    @Column(name="EmbossedSerialNumber", length=40)
    public String getEmbossedSerialNumber() {
        return this.embossedSerialNumber;
    }
    
    public void setEmbossedSerialNumber(String embossedSerialNumber) {
        this.embossedSerialNumber = embossedSerialNumber;
    }

    
    @Column(name="ComplationId", nullable=false, length=40)
    public String getComplationId() {
        return this.complationId;
    }
    
    public void setComplationId(String complationId) {
        this.complationId = complationId;
    }

    
    @Column(name="ConditionId", nullable=false, length=40)
    public String getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }

    
    @Column(name="StatusId", nullable=false, length=40)
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SuppWarrantyStart", length=23)
    public Date getSuppWarrantyStart() {
        return this.suppWarrantyStart;
    }
    
    public void setSuppWarrantyStart(Date suppWarrantyStart) {
        this.suppWarrantyStart = suppWarrantyStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SuppWarrantyEnd", length=23)
    public Date getSuppWarrantyEnd() {
        return this.suppWarrantyEnd;
    }
    
    public void setSuppWarrantyEnd(Date suppWarrantyEnd) {
        this.suppWarrantyEnd = suppWarrantyEnd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RecievedDate", length=23)
    public Date getRecievedDate() {
        return this.recievedDate;
    }
    
    public void setRecievedDate(Date recievedDate) {
        this.recievedDate = recievedDate;
    }

    
    @Column(name="RecieveBy", length=20)
    public String getRecieveBy() {
        return this.recieveBy;
    }
    
    public void setRecieveBy(String recieveBy) {
        this.recieveBy = recieveBy;
    }

    
    @Column(name="SupplierPoNumber", length=40)
    public String getSupplierPoNumber() {
        return this.supplierPoNumber;
    }
    
    public void setSupplierPoNumber(String supplierPoNumber) {
        this.supplierPoNumber = supplierPoNumber;
    }

    
    @Column(name="GoodRecievedNo", length=100)
    public String getGoodRecievedNo() {
        return this.goodRecievedNo;
    }
    
    public void setGoodRecievedNo(String goodRecievedNo) {
        this.goodRecievedNo = goodRecievedNo;
    }

    
    @Column(name="IsReservation")
    public Boolean getIsReservation() {
        return this.isReservation;
    }
    
    public void setIsReservation(Boolean isReservation) {
        this.isReservation = isReservation;
    }

    
    @Column(name="IsReceived")
    public Boolean getIsReceived() {
        return this.isReceived;
    }
    
    public void setIsReceived(Boolean isReceived) {
        this.isReceived = isReceived;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loMaterialInbound")
    public Set getLoDeliveryOrders() {
        return this.loDeliveryOrders;
    }
    
    public void setLoDeliveryOrders(Set loDeliveryOrders) {
        this.loDeliveryOrders = loDeliveryOrders;
    }




}


