package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoWarehouse generated by hbm2java
 */
@Entity
@Table(name="LoWarehouse"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class LoWarehouse  implements java.io.Serializable {


     private String warehouseId;
     private String productId;
     private String warehouseName;
     private String warehouseNameShort;
     private Boolean isExists;
     private Boolean isVirtual;
     private Boolean isDashboard;
     private String createdBy;
     private Date createdDate;
     private Set loMaterialInbounds = new HashSet(0);

    public LoWarehouse() {
    }

	
    public LoWarehouse(String warehouseId, String productId) {
        this.warehouseId = warehouseId;
        this.productId = productId;
    }
    public LoWarehouse(String warehouseId, String productId, String warehouseName, String warehouseNameShort, Boolean isExists, Boolean isVirtual, Boolean isDashboard, String createdBy, Date createdDate, Set loMaterialInbounds) {
       this.warehouseId = warehouseId;
       this.productId = productId;
       this.warehouseName = warehouseName;
       this.warehouseNameShort = warehouseNameShort;
       this.isExists = isExists;
       this.isVirtual = isVirtual;
       this.isDashboard = isDashboard;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.loMaterialInbounds = loMaterialInbounds;
    }
   
     @Id 

    
    @Column(name="WarehouseId", unique=true, nullable=false, length=40)
    public String getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="WarehouseName", length=100)
    public String getWarehouseName() {
        return this.warehouseName;
    }
    
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    
    @Column(name="WarehouseNameShort", length=20)
    public String getWarehouseNameShort() {
        return this.warehouseNameShort;
    }
    
    public void setWarehouseNameShort(String warehouseNameShort) {
        this.warehouseNameShort = warehouseNameShort;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="IsVirtual")
    public Boolean getIsVirtual() {
        return this.isVirtual;
    }
    
    public void setIsVirtual(Boolean isVirtual) {
        this.isVirtual = isVirtual;
    }

    
    @Column(name="IsDashboard")
    public Boolean getIsDashboard() {
        return this.isDashboard;
    }
    
    public void setIsDashboard(Boolean isDashboard) {
        this.isDashboard = isDashboard;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loWarehouse")
    public Set getLoMaterialInbounds() {
        return this.loMaterialInbounds;
    }
    
    public void setLoMaterialInbounds(Set loMaterialInbounds) {
        this.loMaterialInbounds = loMaterialInbounds;
    }




}


