package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialReturnDetail generated by hbm2java
 */
@Entity
@Table(name="MaterialReturnDetail"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class MaterialReturnDetail  implements java.io.Serializable {


     private String materialReturnDetailId;
     private String materialReturnId;
     private String deliveryOrderId;
     private String materialSerialNumber;
     private String parentSerialNumber;
     private Date eventDate;
     private String eventStatusId;
     private String eventConditionId;
     private String returnReason;
     private String returnBy;
     private String actualSlboqid;
     private String actualRegionId;
     private String actualAreaId;
     private String actualSiteId;
     private Boolean isReceived;
     private Integer createdBy;
     private Date createdDate;

    public MaterialReturnDetail() {
    }

	
    public MaterialReturnDetail(String materialReturnDetailId, String materialReturnId, String materialSerialNumber) {
        this.materialReturnDetailId = materialReturnDetailId;
        this.materialReturnId = materialReturnId;
        this.materialSerialNumber = materialSerialNumber;
    }
    public MaterialReturnDetail(String materialReturnDetailId, String materialReturnId, String deliveryOrderId, String materialSerialNumber, String parentSerialNumber, Date eventDate, String eventStatusId, String eventConditionId, String returnReason, String returnBy, String actualSlboqid, String actualRegionId, String actualAreaId, String actualSiteId, Boolean isReceived, Integer createdBy, Date createdDate) {
       this.materialReturnDetailId = materialReturnDetailId;
       this.materialReturnId = materialReturnId;
       this.deliveryOrderId = deliveryOrderId;
       this.materialSerialNumber = materialSerialNumber;
       this.parentSerialNumber = parentSerialNumber;
       this.eventDate = eventDate;
       this.eventStatusId = eventStatusId;
       this.eventConditionId = eventConditionId;
       this.returnReason = returnReason;
       this.returnBy = returnBy;
       this.actualSlboqid = actualSlboqid;
       this.actualRegionId = actualRegionId;
       this.actualAreaId = actualAreaId;
       this.actualSiteId = actualSiteId;
       this.isReceived = isReceived;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="MaterialReturnDetailId", unique=true, nullable=false, length=36)
    public String getMaterialReturnDetailId() {
        return this.materialReturnDetailId;
    }
    
    public void setMaterialReturnDetailId(String materialReturnDetailId) {
        this.materialReturnDetailId = materialReturnDetailId;
    }

    
    @Column(name="MaterialReturnId", nullable=false, length=30)
    public String getMaterialReturnId() {
        return this.materialReturnId;
    }
    
    public void setMaterialReturnId(String materialReturnId) {
        this.materialReturnId = materialReturnId;
    }

    
    @Column(name="DeliveryOrderId", length=30)
    public String getDeliveryOrderId() {
        return this.deliveryOrderId;
    }
    
    public void setDeliveryOrderId(String deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId;
    }

    
    @Column(name="MaterialSerialNumber", nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EventDate", length=23)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    
    @Column(name="EventStatusId", length=40)
    public String getEventStatusId() {
        return this.eventStatusId;
    }
    
    public void setEventStatusId(String eventStatusId) {
        this.eventStatusId = eventStatusId;
    }

    
    @Column(name="EventConditionId", length=40)
    public String getEventConditionId() {
        return this.eventConditionId;
    }
    
    public void setEventConditionId(String eventConditionId) {
        this.eventConditionId = eventConditionId;
    }

    
    @Column(name="ReturnReason", length=250)
    public String getReturnReason() {
        return this.returnReason;
    }
    
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason;
    }

    
    @Column(name="ReturnBy", length=100)
    public String getReturnBy() {
        return this.returnBy;
    }
    
    public void setReturnBy(String returnBy) {
        this.returnBy = returnBy;
    }

    
    @Column(name="ActualSLBOQId", length=36)
    public String getActualSlboqid() {
        return this.actualSlboqid;
    }
    
    public void setActualSlboqid(String actualSlboqid) {
        this.actualSlboqid = actualSlboqid;
    }

    
    @Column(name="ActualRegionId", length=40)
    public String getActualRegionId() {
        return this.actualRegionId;
    }
    
    public void setActualRegionId(String actualRegionId) {
        this.actualRegionId = actualRegionId;
    }

    
    @Column(name="ActualAreaId", length=40)
    public String getActualAreaId() {
        return this.actualAreaId;
    }
    
    public void setActualAreaId(String actualAreaId) {
        this.actualAreaId = actualAreaId;
    }

    
    @Column(name="ActualSiteId", length=40)
    public String getActualSiteId() {
        return this.actualSiteId;
    }
    
    public void setActualSiteId(String actualSiteId) {
        this.actualSiteId = actualSiteId;
    }

    
    @Column(name="IsReceived")
    public Boolean getIsReceived() {
        return this.isReceived;
    }
    
    public void setIsReceived(Boolean isReceived) {
        this.isReceived = isReceived;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


