package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialTrackingHistory generated by hbm2java
 */
@Entity
@Table(name="MaterialTrackingHistory"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class MaterialTrackingHistory  implements java.io.Serializable {


     private String materialTrackingHistoryId;
     private MaterialTrackingHistory materialTrackingHistory;
     private Date trackingDate;
     private String trackFlag;
     private String mainFormId;
     private String mainFormType;
     private String warehouseId;
     private String regionId;
     private String areaId;
     private String siteId;
     private String materialGroupId;
     private String materialTypeId;
     private String materialSerialNumber;
     private String conditionId;
     private Set materialTrackingHistories = new HashSet(0);

    public MaterialTrackingHistory() {
    }

	
    public MaterialTrackingHistory(String materialTrackingHistoryId) {
        this.materialTrackingHistoryId = materialTrackingHistoryId;
    }
    public MaterialTrackingHistory(String materialTrackingHistoryId, MaterialTrackingHistory materialTrackingHistory, Date trackingDate, String trackFlag, String mainFormId, String mainFormType, String warehouseId, String regionId, String areaId, String siteId, String materialGroupId, String materialTypeId, String materialSerialNumber, String conditionId, Set materialTrackingHistories) {
       this.materialTrackingHistoryId = materialTrackingHistoryId;
       this.materialTrackingHistory = materialTrackingHistory;
       this.trackingDate = trackingDate;
       this.trackFlag = trackFlag;
       this.mainFormId = mainFormId;
       this.mainFormType = mainFormType;
       this.warehouseId = warehouseId;
       this.regionId = regionId;
       this.areaId = areaId;
       this.siteId = siteId;
       this.materialGroupId = materialGroupId;
       this.materialTypeId = materialTypeId;
       this.materialSerialNumber = materialSerialNumber;
       this.conditionId = conditionId;
       this.materialTrackingHistories = materialTrackingHistories;
    }
   
     @Id 

    
    @Column(name="MaterialTrackingHistoryId", unique=true, nullable=false, length=40)
    public String getMaterialTrackingHistoryId() {
        return this.materialTrackingHistoryId;
    }
    
    public void setMaterialTrackingHistoryId(String materialTrackingHistoryId) {
        this.materialTrackingHistoryId = materialTrackingHistoryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ParentDetailId")
    public MaterialTrackingHistory getMaterialTrackingHistory() {
        return this.materialTrackingHistory;
    }
    
    public void setMaterialTrackingHistory(MaterialTrackingHistory materialTrackingHistory) {
        this.materialTrackingHistory = materialTrackingHistory;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TrackingDate", length=23)
    public Date getTrackingDate() {
        return this.trackingDate;
    }
    
    public void setTrackingDate(Date trackingDate) {
        this.trackingDate = trackingDate;
    }

    
    @Column(name="TrackFlag", length=40)
    public String getTrackFlag() {
        return this.trackFlag;
    }
    
    public void setTrackFlag(String trackFlag) {
        this.trackFlag = trackFlag;
    }

    
    @Column(name="MainFormId", length=40)
    public String getMainFormId() {
        return this.mainFormId;
    }
    
    public void setMainFormId(String mainFormId) {
        this.mainFormId = mainFormId;
    }

    
    @Column(name="MainFormType", length=40)
    public String getMainFormType() {
        return this.mainFormType;
    }
    
    public void setMainFormType(String mainFormType) {
        this.mainFormType = mainFormType;
    }

    
    @Column(name="WarehouseId", length=40)
    public String getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }

    
    @Column(name="RegionId", length=40)
    public String getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="AreaId", length=40)
    public String getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    
    @Column(name="SiteId", length=40)
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    
    @Column(name="MaterialGroupId", length=40)
    public String getMaterialGroupId() {
        return this.materialGroupId;
    }
    
    public void setMaterialGroupId(String materialGroupId) {
        this.materialGroupId = materialGroupId;
    }

    
    @Column(name="MaterialTypeId", length=40)
    public String getMaterialTypeId() {
        return this.materialTypeId;
    }
    
    public void setMaterialTypeId(String materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    
    @Column(name="MaterialSerialNumber", length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="ConditionId", length=40)
    public String getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materialTrackingHistory")
    public Set getMaterialTrackingHistories() {
        return this.materialTrackingHistories;
    }
    
    public void setMaterialTrackingHistories(Set materialTrackingHistories) {
        this.materialTrackingHistories = materialTrackingHistories;
    }




}


