package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialTransferDetail generated by hbm2java
 */
@Entity
@Table(name="MaterialTransferDetail"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class MaterialTransferDetail  implements java.io.Serializable {


     private String materialTransferDetailId;
     private String materialTransferId;
     private String materialSerialNumber;
     private String parentSerialNumber;
     private Date eventDate;
     private String eventStatusId;
     private String idCondition;
     private String fromWarehouseId;
     private String transferReason;
     private Integer createdBy;
     private Date createdDate;

    public MaterialTransferDetail() {
    }

	
    public MaterialTransferDetail(String materialTransferDetailId, String materialTransferId, String materialSerialNumber) {
        this.materialTransferDetailId = materialTransferDetailId;
        this.materialTransferId = materialTransferId;
        this.materialSerialNumber = materialSerialNumber;
    }
    public MaterialTransferDetail(String materialTransferDetailId, String materialTransferId, String materialSerialNumber, String parentSerialNumber, Date eventDate, String eventStatusId, String idCondition, String fromWarehouseId, String transferReason, Integer createdBy, Date createdDate) {
       this.materialTransferDetailId = materialTransferDetailId;
       this.materialTransferId = materialTransferId;
       this.materialSerialNumber = materialSerialNumber;
       this.parentSerialNumber = parentSerialNumber;
       this.eventDate = eventDate;
       this.eventStatusId = eventStatusId;
       this.idCondition = idCondition;
       this.fromWarehouseId = fromWarehouseId;
       this.transferReason = transferReason;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="MaterialTransferDetailId", unique=true, nullable=false, length=36)
    public String getMaterialTransferDetailId() {
        return this.materialTransferDetailId;
    }
    
    public void setMaterialTransferDetailId(String materialTransferDetailId) {
        this.materialTransferDetailId = materialTransferDetailId;
    }

    
    @Column(name="MaterialTransferId", nullable=false, length=30)
    public String getMaterialTransferId() {
        return this.materialTransferId;
    }
    
    public void setMaterialTransferId(String materialTransferId) {
        this.materialTransferId = materialTransferId;
    }

    
    @Column(name="MaterialSerialNumber", nullable=false, length=40)
    public String getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(String materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="ParentSerialNumber", length=40)
    public String getParentSerialNumber() {
        return this.parentSerialNumber;
    }
    
    public void setParentSerialNumber(String parentSerialNumber) {
        this.parentSerialNumber = parentSerialNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EventDate", length=23)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    
    @Column(name="EventStatusId", length=40)
    public String getEventStatusId() {
        return this.eventStatusId;
    }
    
    public void setEventStatusId(String eventStatusId) {
        this.eventStatusId = eventStatusId;
    }

    
    @Column(name="IdCondition", length=40)
    public String getIdCondition() {
        return this.idCondition;
    }
    
    public void setIdCondition(String idCondition) {
        this.idCondition = idCondition;
    }

    
    @Column(name="FromWarehouseId", length=40)
    public String getFromWarehouseId() {
        return this.fromWarehouseId;
    }
    
    public void setFromWarehouseId(String fromWarehouseId) {
        this.fromWarehouseId = fromWarehouseId;
    }

    
    @Column(name="TransferReason", length=250)
    public String getTransferReason() {
        return this.transferReason;
    }
    
    public void setTransferReason(String transferReason) {
        this.transferReason = transferReason;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


