package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldTransactionDetail generated by hbm2java
 */
@Entity
@Table(name="Old_TransactionDetail"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class OldTransactionDetail  implements java.io.Serializable {


     private String transactionDetailId;
     private LoMaterialGroup loMaterialGroup;
     private LoMaterialType loMaterialType;
     private TransactionHeader transactionHeader;
     private Integer materialQuantity;
     private Boolean isExists;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;

    public OldTransactionDetail() {
    }

	
    public OldTransactionDetail(String transactionDetailId, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, TransactionHeader transactionHeader) {
        this.transactionDetailId = transactionDetailId;
        this.loMaterialGroup = loMaterialGroup;
        this.loMaterialType = loMaterialType;
        this.transactionHeader = transactionHeader;
    }
    public OldTransactionDetail(String transactionDetailId, LoMaterialGroup loMaterialGroup, LoMaterialType loMaterialType, TransactionHeader transactionHeader, Integer materialQuantity, Boolean isExists, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate) {
       this.transactionDetailId = transactionDetailId;
       this.loMaterialGroup = loMaterialGroup;
       this.loMaterialType = loMaterialType;
       this.transactionHeader = transactionHeader;
       this.materialQuantity = materialQuantity;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id 

    
    @Column(name="TransactionDetailId", unique=true, nullable=false, length=40)
    public String getTransactionDetailId() {
        return this.transactionDetailId;
    }
    
    public void setTransactionDetailId(String transactionDetailId) {
        this.transactionDetailId = transactionDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialGroupId", nullable=false)
    public LoMaterialGroup getLoMaterialGroup() {
        return this.loMaterialGroup;
    }
    
    public void setLoMaterialGroup(LoMaterialGroup loMaterialGroup) {
        this.loMaterialGroup = loMaterialGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaterialTypeId", nullable=false)
    public LoMaterialType getLoMaterialType() {
        return this.loMaterialType;
    }
    
    public void setLoMaterialType(LoMaterialType loMaterialType) {
        this.loMaterialType = loMaterialType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MainFormId", nullable=false)
    public TransactionHeader getTransactionHeader() {
        return this.transactionHeader;
    }
    
    public void setTransactionHeader(TransactionHeader transactionHeader) {
        this.transactionHeader = transactionHeader;
    }

    
    @Column(name="MaterialQuantity")
    public Integer getMaterialQuantity() {
        return this.materialQuantity;
    }
    
    public void setMaterialQuantity(Integer materialQuantity) {
        this.materialQuantity = materialQuantity;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


