package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProSiteProgress generated by hbm2java
 */
@Entity
@Table(name="ProSiteProgress"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class ProSiteProgress  implements java.io.Serializable {


     private String siteProgressId;
     private Slboq slboq;
     private String projectTask;
     private String mainFormId;
     private Date lastUpdateDate;
     private Integer lastUpdateBy;
     private Boolean isActive;
     private Boolean isExists;
     private String projectStatusId;
     private Set proSiteInstalleds = new HashSet(0);

    public ProSiteProgress() {
    }

	
    public ProSiteProgress(String siteProgressId, Slboq slboq) {
        this.siteProgressId = siteProgressId;
        this.slboq = slboq;
    }
    public ProSiteProgress(String siteProgressId, Slboq slboq, String projectTask, String mainFormId, Date lastUpdateDate, Integer lastUpdateBy, Boolean isActive, Boolean isExists, String projectStatusId, Set proSiteInstalleds) {
       this.siteProgressId = siteProgressId;
       this.slboq = slboq;
       this.projectTask = projectTask;
       this.mainFormId = mainFormId;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateBy = lastUpdateBy;
       this.isActive = isActive;
       this.isExists = isExists;
       this.projectStatusId = projectStatusId;
       this.proSiteInstalleds = proSiteInstalleds;
    }
   
     @Id 

    
    @Column(name="SiteProgressId", unique=true, nullable=false, length=40)
    public String getSiteProgressId() {
        return this.siteProgressId;
    }
    
    public void setSiteProgressId(String siteProgressId) {
        this.siteProgressId = siteProgressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SLBOQId", nullable=false)
    public Slboq getSlboq() {
        return this.slboq;
    }
    
    public void setSlboq(Slboq slboq) {
        this.slboq = slboq;
    }

    
    @Column(name="ProjectTask", length=100)
    public String getProjectTask() {
        return this.projectTask;
    }
    
    public void setProjectTask(String projectTask) {
        this.projectTask = projectTask;
    }

    
    @Column(name="MainFormId", length=40)
    public String getMainFormId() {
        return this.mainFormId;
    }
    
    public void setMainFormId(String mainFormId) {
        this.mainFormId = mainFormId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateDate", length=23)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    
    @Column(name="LastUpdateBy")
    public Integer getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(Integer lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="ProjectStatusId", length=40)
    public String getProjectStatusId() {
        return this.projectStatusId;
    }
    
    public void setProjectStatusId(String projectStatusId) {
        this.projectStatusId = projectStatusId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proSiteProgress")
    public Set getProSiteInstalleds() {
        return this.proSiteInstalleds;
    }
    
    public void setProSiteInstalleds(Set proSiteInstalleds) {
        this.proSiteInstalleds = proSiteInstalleds;
    }




}


