package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProSiteInstalled generated by hbm2java
 */
@Entity
@Table(name="ProSiteInstalled"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class ProSiteInstalled  implements java.io.Serializable {


     private String siteInstalledId;
     private ProSiteProgress proSiteProgress;
     private String slboqid;
     private String mainFormId;
     private String compId;
     private Date installedDate;
     private String installedBy;
     private String mobilePhone;
     private String installedReason;
     private Date atpdate;
     private String atpreason;
     private Date bautSubmit;
     private String bautNo;
     private Date bautDate;
     private String bautReason;
     private String crno;
     private Date crdate;
     private String cono;
     private Date codate;
     private Date codateApproved;
     private String coapprovedBy;
     private String coapprovedTitle;
     private String bastNo;
     private Date bastSubmitDate;
     private Date bastApprovalDate;
     private String invoiceNo;
     private Date invoiceDate;
     private Date invoiceSubmitDate;
     private String bapkNo;
     private Date bapkDate;
     private Boolean isLockInstalled;
     private Boolean isLockAtp;
     private Boolean isLockBaut;
     private Boolean isLockCr;
     private Boolean isLockCo;
     private Boolean isLockBast;
     private Boolean isLockInvoice;
     private Boolean isExists;
     private Set proSitePrices = new HashSet(0);

    public ProSiteInstalled() {
    }

	
    public ProSiteInstalled(String siteInstalledId, ProSiteProgress proSiteProgress, String slboqid) {
        this.siteInstalledId = siteInstalledId;
        this.proSiteProgress = proSiteProgress;
        this.slboqid = slboqid;
    }
    public ProSiteInstalled(String siteInstalledId, ProSiteProgress proSiteProgress, String slboqid, String mainFormId, String compId, Date installedDate, String installedBy, String mobilePhone, String installedReason, Date atpdate, String atpreason, Date bautSubmit, String bautNo, Date bautDate, String bautReason, String crno, Date crdate, String cono, Date codate, Date codateApproved, String coapprovedBy, String coapprovedTitle, String bastNo, Date bastSubmitDate, Date bastApprovalDate, String invoiceNo, Date invoiceDate, Date invoiceSubmitDate, String bapkNo, Date bapkDate, Boolean isLockInstalled, Boolean isLockAtp, Boolean isLockBaut, Boolean isLockCr, Boolean isLockCo, Boolean isLockBast, Boolean isLockInvoice, Boolean isExists, Set proSitePrices) {
       this.siteInstalledId = siteInstalledId;
       this.proSiteProgress = proSiteProgress;
       this.slboqid = slboqid;
       this.mainFormId = mainFormId;
       this.compId = compId;
       this.installedDate = installedDate;
       this.installedBy = installedBy;
       this.mobilePhone = mobilePhone;
       this.installedReason = installedReason;
       this.atpdate = atpdate;
       this.atpreason = atpreason;
       this.bautSubmit = bautSubmit;
       this.bautNo = bautNo;
       this.bautDate = bautDate;
       this.bautReason = bautReason;
       this.crno = crno;
       this.crdate = crdate;
       this.cono = cono;
       this.codate = codate;
       this.codateApproved = codateApproved;
       this.coapprovedBy = coapprovedBy;
       this.coapprovedTitle = coapprovedTitle;
       this.bastNo = bastNo;
       this.bastSubmitDate = bastSubmitDate;
       this.bastApprovalDate = bastApprovalDate;
       this.invoiceNo = invoiceNo;
       this.invoiceDate = invoiceDate;
       this.invoiceSubmitDate = invoiceSubmitDate;
       this.bapkNo = bapkNo;
       this.bapkDate = bapkDate;
       this.isLockInstalled = isLockInstalled;
       this.isLockAtp = isLockAtp;
       this.isLockBaut = isLockBaut;
       this.isLockCr = isLockCr;
       this.isLockCo = isLockCo;
       this.isLockBast = isLockBast;
       this.isLockInvoice = isLockInvoice;
       this.isExists = isExists;
       this.proSitePrices = proSitePrices;
    }
   
     @Id 

    
    @Column(name="SiteInstalledId", unique=true, nullable=false, length=40)
    public String getSiteInstalledId() {
        return this.siteInstalledId;
    }
    
    public void setSiteInstalledId(String siteInstalledId) {
        this.siteInstalledId = siteInstalledId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SiteProgressId", nullable=false)
    public ProSiteProgress getProSiteProgress() {
        return this.proSiteProgress;
    }
    
    public void setProSiteProgress(ProSiteProgress proSiteProgress) {
        this.proSiteProgress = proSiteProgress;
    }

    
    @Column(name="SLBOQId", nullable=false, length=36)
    public String getSlboqid() {
        return this.slboqid;
    }
    
    public void setSlboqid(String slboqid) {
        this.slboqid = slboqid;
    }

    
    @Column(name="MainFormId", length=40)
    public String getMainFormId() {
        return this.mainFormId;
    }
    
    public void setMainFormId(String mainFormId) {
        this.mainFormId = mainFormId;
    }

    
    @Column(name="CompId", length=40)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InstalledDate", length=23)
    public Date getInstalledDate() {
        return this.installedDate;
    }
    
    public void setInstalledDate(Date installedDate) {
        this.installedDate = installedDate;
    }

    
    @Column(name="InstalledBy", length=100)
    public String getInstalledBy() {
        return this.installedBy;
    }
    
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    
    @Column(name="MobilePhone", length=40)
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    
    @Column(name="InstalledReason", length=250)
    public String getInstalledReason() {
        return this.installedReason;
    }
    
    public void setInstalledReason(String installedReason) {
        this.installedReason = installedReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ATPDate", length=23)
    public Date getAtpdate() {
        return this.atpdate;
    }
    
    public void setAtpdate(Date atpdate) {
        this.atpdate = atpdate;
    }

    
    @Column(name="ATPReason", length=250)
    public String getAtpreason() {
        return this.atpreason;
    }
    
    public void setAtpreason(String atpreason) {
        this.atpreason = atpreason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BautSubmit", length=23)
    public Date getBautSubmit() {
        return this.bautSubmit;
    }
    
    public void setBautSubmit(Date bautSubmit) {
        this.bautSubmit = bautSubmit;
    }

    
    @Column(name="BautNo", length=100)
    public String getBautNo() {
        return this.bautNo;
    }
    
    public void setBautNo(String bautNo) {
        this.bautNo = bautNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BautDate", length=23)
    public Date getBautDate() {
        return this.bautDate;
    }
    
    public void setBautDate(Date bautDate) {
        this.bautDate = bautDate;
    }

    
    @Column(name="BautReason", length=250)
    public String getBautReason() {
        return this.bautReason;
    }
    
    public void setBautReason(String bautReason) {
        this.bautReason = bautReason;
    }

    
    @Column(name="CRNo", length=100)
    public String getCrno() {
        return this.crno;
    }
    
    public void setCrno(String crno) {
        this.crno = crno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CRDate", length=23)
    public Date getCrdate() {
        return this.crdate;
    }
    
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    
    @Column(name="CONo", length=100)
    public String getCono() {
        return this.cono;
    }
    
    public void setCono(String cono) {
        this.cono = cono;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CODate", length=23)
    public Date getCodate() {
        return this.codate;
    }
    
    public void setCodate(Date codate) {
        this.codate = codate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CODateApproved", length=23)
    public Date getCodateApproved() {
        return this.codateApproved;
    }
    
    public void setCodateApproved(Date codateApproved) {
        this.codateApproved = codateApproved;
    }

    
    @Column(name="COApprovedBy", length=100)
    public String getCoapprovedBy() {
        return this.coapprovedBy;
    }
    
    public void setCoapprovedBy(String coapprovedBy) {
        this.coapprovedBy = coapprovedBy;
    }

    
    @Column(name="COApprovedTitle", length=100)
    public String getCoapprovedTitle() {
        return this.coapprovedTitle;
    }
    
    public void setCoapprovedTitle(String coapprovedTitle) {
        this.coapprovedTitle = coapprovedTitle;
    }

    
    @Column(name="BastNo", length=100)
    public String getBastNo() {
        return this.bastNo;
    }
    
    public void setBastNo(String bastNo) {
        this.bastNo = bastNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BastSubmitDate", length=23)
    public Date getBastSubmitDate() {
        return this.bastSubmitDate;
    }
    
    public void setBastSubmitDate(Date bastSubmitDate) {
        this.bastSubmitDate = bastSubmitDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BastApprovalDate", length=23)
    public Date getBastApprovalDate() {
        return this.bastApprovalDate;
    }
    
    public void setBastApprovalDate(Date bastApprovalDate) {
        this.bastApprovalDate = bastApprovalDate;
    }

    
    @Column(name="InvoiceNo", length=100)
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InvoiceDate", length=23)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InvoiceSubmitDate", length=23)
    public Date getInvoiceSubmitDate() {
        return this.invoiceSubmitDate;
    }
    
    public void setInvoiceSubmitDate(Date invoiceSubmitDate) {
        this.invoiceSubmitDate = invoiceSubmitDate;
    }

    
    @Column(name="BapkNo", length=100)
    public String getBapkNo() {
        return this.bapkNo;
    }
    
    public void setBapkNo(String bapkNo) {
        this.bapkNo = bapkNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BapkDate", length=23)
    public Date getBapkDate() {
        return this.bapkDate;
    }
    
    public void setBapkDate(Date bapkDate) {
        this.bapkDate = bapkDate;
    }

    
    @Column(name="IsLockInstalled")
    public Boolean getIsLockInstalled() {
        return this.isLockInstalled;
    }
    
    public void setIsLockInstalled(Boolean isLockInstalled) {
        this.isLockInstalled = isLockInstalled;
    }

    
    @Column(name="IsLockATP")
    public Boolean getIsLockAtp() {
        return this.isLockAtp;
    }
    
    public void setIsLockAtp(Boolean isLockAtp) {
        this.isLockAtp = isLockAtp;
    }

    
    @Column(name="IsLockBaut")
    public Boolean getIsLockBaut() {
        return this.isLockBaut;
    }
    
    public void setIsLockBaut(Boolean isLockBaut) {
        this.isLockBaut = isLockBaut;
    }

    
    @Column(name="IsLockCr")
    public Boolean getIsLockCr() {
        return this.isLockCr;
    }
    
    public void setIsLockCr(Boolean isLockCr) {
        this.isLockCr = isLockCr;
    }

    
    @Column(name="IsLockCo")
    public Boolean getIsLockCo() {
        return this.isLockCo;
    }
    
    public void setIsLockCo(Boolean isLockCo) {
        this.isLockCo = isLockCo;
    }

    
    @Column(name="IsLockBast")
    public Boolean getIsLockBast() {
        return this.isLockBast;
    }
    
    public void setIsLockBast(Boolean isLockBast) {
        this.isLockBast = isLockBast;
    }

    
    @Column(name="IsLockInvoice")
    public Boolean getIsLockInvoice() {
        return this.isLockInvoice;
    }
    
    public void setIsLockInvoice(Boolean isLockInvoice) {
        this.isLockInvoice = isLockInvoice;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proSiteInstalled")
    public Set getProSitePrices() {
        return this.proSitePrices;
    }
    
    public void setProSitePrices(Set proSitePrices) {
        this.proSitePrices = proSitePrices;
    }




}


