package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PtSiteProgress generated by hbm2java
 */
@Entity
@Table(name="PtSiteProgress"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class PtSiteProgress  implements java.io.Serializable {


     private String siteProgressId;
     private TransactionHeader transactionHeader;
     private Date installedDate;
     private String installedBy;
     private String installedContactPhone;
     private String installedLateReason;
     private Date atpdate;
     private String atplateReason;
     private String bautnumber;
     private Date bautdate;
     private Date bautsubmit;
     private String siteStatusId;
     private Boolean isChangeRequest;
     private String changeApproved1;
     private String changeApproved2;

    public PtSiteProgress() {
    }

	
    public PtSiteProgress(String siteProgressId, TransactionHeader transactionHeader) {
        this.siteProgressId = siteProgressId;
        this.transactionHeader = transactionHeader;
    }
    public PtSiteProgress(String siteProgressId, TransactionHeader transactionHeader, Date installedDate, String installedBy, String installedContactPhone, String installedLateReason, Date atpdate, String atplateReason, String bautnumber, Date bautdate, Date bautsubmit, String siteStatusId, Boolean isChangeRequest, String changeApproved1, String changeApproved2) {
       this.siteProgressId = siteProgressId;
       this.transactionHeader = transactionHeader;
       this.installedDate = installedDate;
       this.installedBy = installedBy;
       this.installedContactPhone = installedContactPhone;
       this.installedLateReason = installedLateReason;
       this.atpdate = atpdate;
       this.atplateReason = atplateReason;
       this.bautnumber = bautnumber;
       this.bautdate = bautdate;
       this.bautsubmit = bautsubmit;
       this.siteStatusId = siteStatusId;
       this.isChangeRequest = isChangeRequest;
       this.changeApproved1 = changeApproved1;
       this.changeApproved2 = changeApproved2;
    }
   
     @Id 

    
    @Column(name="SiteProgressId", unique=true, nullable=false, length=40)
    public String getSiteProgressId() {
        return this.siteProgressId;
    }
    
    public void setSiteProgressId(String siteProgressId) {
        this.siteProgressId = siteProgressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MainFormId", nullable=false)
    public TransactionHeader getTransactionHeader() {
        return this.transactionHeader;
    }
    
    public void setTransactionHeader(TransactionHeader transactionHeader) {
        this.transactionHeader = transactionHeader;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InstalledDate", length=23)
    public Date getInstalledDate() {
        return this.installedDate;
    }
    
    public void setInstalledDate(Date installedDate) {
        this.installedDate = installedDate;
    }

    
    @Column(name="InstalledBy", length=20)
    public String getInstalledBy() {
        return this.installedBy;
    }
    
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    
    @Column(name="InstalledContactPhone", length=40)
    public String getInstalledContactPhone() {
        return this.installedContactPhone;
    }
    
    public void setInstalledContactPhone(String installedContactPhone) {
        this.installedContactPhone = installedContactPhone;
    }

    
    @Column(name="InstalledLateReason", length=250)
    public String getInstalledLateReason() {
        return this.installedLateReason;
    }
    
    public void setInstalledLateReason(String installedLateReason) {
        this.installedLateReason = installedLateReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ATPDate", length=23)
    public Date getAtpdate() {
        return this.atpdate;
    }
    
    public void setAtpdate(Date atpdate) {
        this.atpdate = atpdate;
    }

    
    @Column(name="ATPLateReason", length=250)
    public String getAtplateReason() {
        return this.atplateReason;
    }
    
    public void setAtplateReason(String atplateReason) {
        this.atplateReason = atplateReason;
    }

    
    @Column(name="BAUTNumber", length=200)
    public String getBautnumber() {
        return this.bautnumber;
    }
    
    public void setBautnumber(String bautnumber) {
        this.bautnumber = bautnumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BAUTDate", length=23)
    public Date getBautdate() {
        return this.bautdate;
    }
    
    public void setBautdate(Date bautdate) {
        this.bautdate = bautdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BAUTSubmit", length=23)
    public Date getBautsubmit() {
        return this.bautsubmit;
    }
    
    public void setBautsubmit(Date bautsubmit) {
        this.bautsubmit = bautsubmit;
    }

    
    @Column(name="SiteStatusId", length=40)
    public String getSiteStatusId() {
        return this.siteStatusId;
    }
    
    public void setSiteStatusId(String siteStatusId) {
        this.siteStatusId = siteStatusId;
    }

    
    @Column(name="IsChangeRequest")
    public Boolean getIsChangeRequest() {
        return this.isChangeRequest;
    }
    
    public void setIsChangeRequest(Boolean isChangeRequest) {
        this.isChangeRequest = isChangeRequest;
    }

    
    @Column(name="ChangeApproved1", length=20)
    public String getChangeApproved1() {
        return this.changeApproved1;
    }
    
    public void setChangeApproved1(String changeApproved1) {
        this.changeApproved1 = changeApproved1;
    }

    
    @Column(name="ChangeApproved2", length=20)
    public String getChangeApproved2() {
        return this.changeApproved2;
    }
    
    public void setChangeApproved2(String changeApproved2) {
        this.changeApproved2 = changeApproved2;
    }




}


