package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Slproject generated by hbm2java
 */
@Entity
@Table(name="SLProject"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class Slproject  implements java.io.Serializable {


     private String slprojectId;
     private SlpurchaseOrder slpurchaseOrder;
     private String slscopeOfWork;
     private Boolean isExists;
     private String productId;
     private Integer createdBy;
     private Date createdDate;
     private Set slsites = new HashSet(0);

    public Slproject() {
    }

	
    public Slproject(String slprojectId, SlpurchaseOrder slpurchaseOrder) {
        this.slprojectId = slprojectId;
        this.slpurchaseOrder = slpurchaseOrder;
    }
    public Slproject(String slprojectId, SlpurchaseOrder slpurchaseOrder, String slscopeOfWork, Boolean isExists, String productId, Integer createdBy, Date createdDate, Set slsites) {
       this.slprojectId = slprojectId;
       this.slpurchaseOrder = slpurchaseOrder;
       this.slscopeOfWork = slscopeOfWork;
       this.isExists = isExists;
       this.productId = productId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.slsites = slsites;
    }
   
     @Id 

    
    @Column(name="SLProjectId", unique=true, nullable=false, length=40)
    public String getSlprojectId() {
        return this.slprojectId;
    }
    
    public void setSlprojectId(String slprojectId) {
        this.slprojectId = slprojectId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SLPONumber", nullable=false)
    public SlpurchaseOrder getSlpurchaseOrder() {
        return this.slpurchaseOrder;
    }
    
    public void setSlpurchaseOrder(SlpurchaseOrder slpurchaseOrder) {
        this.slpurchaseOrder = slpurchaseOrder;
    }

    
    @Column(name="SLScopeOfWork", length=100)
    public String getSlscopeOfWork() {
        return this.slscopeOfWork;
    }
    
    public void setSlscopeOfWork(String slscopeOfWork) {
        this.slscopeOfWork = slscopeOfWork;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CreatedDate", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="slproject")
    public Set getSlsites() {
        return this.slsites;
    }
    
    public void setSlsites(Set slsites) {
        this.slsites = slsites;
    }




}


