package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StCustomerPo generated by hbm2java
 */
@Entity
@Table(name="StCustomerPo"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class StCustomerPo  implements java.io.Serializable {


     private String slponumber;
     private String slponame;
     private Date slpodate;
     private Date slpodueDate;
     private String compId;
     private Boolean isExists;
     private String productId;
     private String createdBy;
     private Date createdDate;
     private Set oldStProjects = new HashSet(0);
     private Set stSalesBoqs = new HashSet(0);

    public StCustomerPo() {
    }

	
    public StCustomerPo(String slponumber) {
        this.slponumber = slponumber;
    }
    public StCustomerPo(String slponumber, String slponame, Date slpodate, Date slpodueDate, String compId, Boolean isExists, String productId, String createdBy, Date createdDate, Set oldStProjects, Set stSalesBoqs) {
       this.slponumber = slponumber;
       this.slponame = slponame;
       this.slpodate = slpodate;
       this.slpodueDate = slpodueDate;
       this.compId = compId;
       this.isExists = isExists;
       this.productId = productId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.oldStProjects = oldStProjects;
       this.stSalesBoqs = stSalesBoqs;
    }
   
     @Id 

    
    @Column(name="SLPONumber", unique=true, nullable=false, length=100)
    public String getSlponumber() {
        return this.slponumber;
    }
    
    public void setSlponumber(String slponumber) {
        this.slponumber = slponumber;
    }

    
    @Column(name="SLPOName")
    public String getSlponame() {
        return this.slponame;
    }
    
    public void setSlponame(String slponame) {
        this.slponame = slponame;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SLPODate", length=23)
    public Date getSlpodate() {
        return this.slpodate;
    }
    
    public void setSlpodate(Date slpodate) {
        this.slpodate = slpodate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SLPODueDate", length=23)
    public Date getSlpodueDate() {
        return this.slpodueDate;
    }
    
    public void setSlpodueDate(Date slpodueDate) {
        this.slpodueDate = slpodueDate;
    }

    
    @Column(name="CompId", length=40)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stCustomerPo")
    public Set getOldStProjects() {
        return this.oldStProjects;
    }
    
    public void setOldStProjects(Set oldStProjects) {
        this.oldStProjects = oldStProjects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stCustomerPo")
    public Set getStSalesBoqs() {
        return this.stSalesBoqs;
    }
    
    public void setStSalesBoqs(Set stSalesBoqs) {
        this.stSalesBoqs = stSalesBoqs;
    }




}


