package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StRegion generated by hbm2java
 */
@Entity
@Table(name="StRegion"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class StRegion  implements java.io.Serializable {


     private String regionId;
     private String regionName;
     private Boolean isExists;
     private String productId;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set stSalesBoqs = new HashSet(0);
     private Set stAreas = new HashSet(0);

    public StRegion() {
    }

	
    public StRegion(String regionId) {
        this.regionId = regionId;
    }
    public StRegion(String regionId, String regionName, Boolean isExists, String productId, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, Set stSalesBoqs, Set stAreas) {
       this.regionId = regionId;
       this.regionName = regionName;
       this.isExists = isExists;
       this.productId = productId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.stSalesBoqs = stSalesBoqs;
       this.stAreas = stAreas;
    }
   
     @Id 

    
    @Column(name="RegionId", unique=true, nullable=false, length=20)
    public String getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="RegionName", length=100)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CreatedDate", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stRegion")
    public Set getStSalesBoqs() {
        return this.stSalesBoqs;
    }
    
    public void setStSalesBoqs(Set stSalesBoqs) {
        this.stSalesBoqs = stSalesBoqs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stRegion")
    public Set getStAreas() {
        return this.stAreas;
    }
    
    public void setStAreas(Set stAreas) {
        this.stAreas = stAreas;
    }




}


