package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StSalesBoq generated by hbm2java
 */
@Entity
@Table(name="StSalesBOQ"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class StSalesBoq  implements java.io.Serializable {


     private String slboqid;
     private StArea stArea;
     private StCustomerPo stCustomerPo;
     private StRegion stRegion;
     private String projectId;
     private String siteId;
     private String idComplation;
     private String scopeOfWork;
     private String configRequirement;
     private String existingConfig;
     private String finalConfigPo;
     private Boolean isExists;
     private String productId;
     private String potype;
     private Boolean isOriginal;
     private String prevPonumber;
     private String createdBy;
     private Date createdDate;

    public StSalesBoq() {
    }

	
    public StSalesBoq(String slboqid, StCustomerPo stCustomerPo, StRegion stRegion, String projectId, String siteId) {
        this.slboqid = slboqid;
        this.stCustomerPo = stCustomerPo;
        this.stRegion = stRegion;
        this.projectId = projectId;
        this.siteId = siteId;
    }
    public StSalesBoq(String slboqid, StArea stArea, StCustomerPo stCustomerPo, StRegion stRegion, String projectId, String siteId, String idComplation, String scopeOfWork, String configRequirement, String existingConfig, String finalConfigPo, Boolean isExists, String productId, String potype, Boolean isOriginal, String prevPonumber, String createdBy, Date createdDate) {
       this.slboqid = slboqid;
       this.stArea = stArea;
       this.stCustomerPo = stCustomerPo;
       this.stRegion = stRegion;
       this.projectId = projectId;
       this.siteId = siteId;
       this.idComplation = idComplation;
       this.scopeOfWork = scopeOfWork;
       this.configRequirement = configRequirement;
       this.existingConfig = existingConfig;
       this.finalConfigPo = finalConfigPo;
       this.isExists = isExists;
       this.productId = productId;
       this.potype = potype;
       this.isOriginal = isOriginal;
       this.prevPonumber = prevPonumber;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="SLBOQId", unique=true, nullable=false, length=36)
    public String getSlboqid() {
        return this.slboqid;
    }
    
    public void setSlboqid(String slboqid) {
        this.slboqid = slboqid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AreaId")
    public StArea getStArea() {
        return this.stArea;
    }
    
    public void setStArea(StArea stArea) {
        this.stArea = stArea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SLPONumber", nullable=false)
    public StCustomerPo getStCustomerPo() {
        return this.stCustomerPo;
    }
    
    public void setStCustomerPo(StCustomerPo stCustomerPo) {
        this.stCustomerPo = stCustomerPo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RegionId", nullable=false)
    public StRegion getStRegion() {
        return this.stRegion;
    }
    
    public void setStRegion(StRegion stRegion) {
        this.stRegion = stRegion;
    }

    
    @Column(name="ProjectId", nullable=false, length=40)
    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="SiteId", nullable=false, length=40)
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    
    @Column(name="IdComplation", length=40)
    public String getIdComplation() {
        return this.idComplation;
    }
    
    public void setIdComplation(String idComplation) {
        this.idComplation = idComplation;
    }

    
    @Column(name="ScopeOfWork", length=100)
    public String getScopeOfWork() {
        return this.scopeOfWork;
    }
    
    public void setScopeOfWork(String scopeOfWork) {
        this.scopeOfWork = scopeOfWork;
    }

    
    @Column(name="ConfigRequirement")
    public String getConfigRequirement() {
        return this.configRequirement;
    }
    
    public void setConfigRequirement(String configRequirement) {
        this.configRequirement = configRequirement;
    }

    
    @Column(name="ExistingConfig")
    public String getExistingConfig() {
        return this.existingConfig;
    }
    
    public void setExistingConfig(String existingConfig) {
        this.existingConfig = existingConfig;
    }

    
    @Column(name="FinalConfigPO")
    public String getFinalConfigPo() {
        return this.finalConfigPo;
    }
    
    public void setFinalConfigPo(String finalConfigPo) {
        this.finalConfigPo = finalConfigPo;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="POType", length=40)
    public String getPotype() {
        return this.potype;
    }
    
    public void setPotype(String potype) {
        this.potype = potype;
    }

    
    @Column(name="IsOriginal")
    public Boolean getIsOriginal() {
        return this.isOriginal;
    }
    
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }

    
    @Column(name="PrevPONumber", length=100)
    public String getPrevPonumber() {
        return this.prevPonumber;
    }
    
    public void setPrevPonumber(String prevPonumber) {
        this.prevPonumber = prevPonumber;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


