package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SyCity generated by hbm2java
 */
@Entity
@Table(name="SyCity"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyCity  implements java.io.Serializable {


     private String cityId;
     private String stateId;
     private String cityName;
     private Boolean isExists;

    public SyCity() {
    }

	
    public SyCity(String cityId, String stateId) {
        this.cityId = cityId;
        this.stateId = stateId;
    }
    public SyCity(String cityId, String stateId, String cityName, Boolean isExists) {
       this.cityId = cityId;
       this.stateId = stateId;
       this.cityName = cityName;
       this.isExists = isExists;
    }
   
     @Id 

    
    @Column(name="CityId", unique=true, nullable=false, length=16)
    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    
    @Column(name="StateId", nullable=false, length=10)
    public String getStateId() {
        return this.stateId;
    }
    
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="CityName", length=100)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }




}


