package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyContactType generated by hbm2java
 */
@Entity
@Table(name="SyContactType"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyContactType  implements java.io.Serializable {


     private int contactTypeId;
     private String contactTypeName;
     private Date createdDate;
     private String createdBy;
     private Date modifiedDate;
     private String modifiedBy;

    public SyContactType() {
    }

	
    public SyContactType(int contactTypeId) {
        this.contactTypeId = contactTypeId;
    }
    public SyContactType(int contactTypeId, String contactTypeName, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
       this.contactTypeId = contactTypeId;
       this.contactTypeName = contactTypeName;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedDate = modifiedDate;
       this.modifiedBy = modifiedBy;
    }
   
     @Id 

    
    @Column(name="ContactTypeId", unique=true, nullable=false)
    public int getContactTypeId() {
        return this.contactTypeId;
    }
    
    public void setContactTypeId(int contactTypeId) {
        this.contactTypeId = contactTypeId;
    }

    
    @Column(name="ContactTypeName", length=100)
    public String getContactTypeName() {
        return this.contactTypeName;
    }
    
    public void setContactTypeName(String contactTypeName) {
        this.contactTypeName = contactTypeName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


