package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyContactPerson generated by hbm2java
 */
@Entity
@Table(name="SyContactPerson"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyContactPerson  implements java.io.Serializable {


     private String contactPersonId;
     private String companyId;
     private String contactPersonName;
     private int contactTypeId;
     private String contactPersonAddress;
     private String countryId;
     private String stateId;
     private String cityId;
     private String contactPersonZip;
     private String contactWorkPhone;
     private String contactHomePhone;
     private String contactCellPhone;
     private String contactPersonEmail;
     private String contactPersonPass;
     private Boolean isLogin;
     private Boolean isDelete;
     private Boolean isConfirm;
     private Boolean isReset;
     private String confirmCode;
     private Date lastDateLogin;
     private String userPrefix;
     private Date createdDate;
     private String createdBy;
     private Date modifiedDate;
     private String modifiedBy;

    public SyContactPerson() {
    }

	
    public SyContactPerson(String contactPersonId, String companyId, int contactTypeId) {
        this.contactPersonId = contactPersonId;
        this.companyId = companyId;
        this.contactTypeId = contactTypeId;
    }
    public SyContactPerson(String contactPersonId, String companyId, String contactPersonName, int contactTypeId, String contactPersonAddress, String countryId, String stateId, String cityId, String contactPersonZip, String contactWorkPhone, String contactHomePhone, String contactCellPhone, String contactPersonEmail, String contactPersonPass, Boolean isLogin, Boolean isDelete, Boolean isConfirm, Boolean isReset, String confirmCode, Date lastDateLogin, String userPrefix, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
       this.contactPersonId = contactPersonId;
       this.companyId = companyId;
       this.contactPersonName = contactPersonName;
       this.contactTypeId = contactTypeId;
       this.contactPersonAddress = contactPersonAddress;
       this.countryId = countryId;
       this.stateId = stateId;
       this.cityId = cityId;
       this.contactPersonZip = contactPersonZip;
       this.contactWorkPhone = contactWorkPhone;
       this.contactHomePhone = contactHomePhone;
       this.contactCellPhone = contactCellPhone;
       this.contactPersonEmail = contactPersonEmail;
       this.contactPersonPass = contactPersonPass;
       this.isLogin = isLogin;
       this.isDelete = isDelete;
       this.isConfirm = isConfirm;
       this.isReset = isReset;
       this.confirmCode = confirmCode;
       this.lastDateLogin = lastDateLogin;
       this.userPrefix = userPrefix;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedDate = modifiedDate;
       this.modifiedBy = modifiedBy;
    }
   
     @Id 

    
    @Column(name="ContactPersonId", unique=true, nullable=false, length=20)
    public String getContactPersonId() {
        return this.contactPersonId;
    }
    
    public void setContactPersonId(String contactPersonId) {
        this.contactPersonId = contactPersonId;
    }

    
    @Column(name="CompanyId", nullable=false, length=15)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="ContactPersonName", length=100)
    public String getContactPersonName() {
        return this.contactPersonName;
    }
    
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }

    
    @Column(name="ContactTypeId", nullable=false)
    public int getContactTypeId() {
        return this.contactTypeId;
    }
    
    public void setContactTypeId(int contactTypeId) {
        this.contactTypeId = contactTypeId;
    }

    
    @Column(name="ContactPersonAddress", length=250)
    public String getContactPersonAddress() {
        return this.contactPersonAddress;
    }
    
    public void setContactPersonAddress(String contactPersonAddress) {
        this.contactPersonAddress = contactPersonAddress;
    }

    
    @Column(name="CountryId", length=6)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="StateId", length=10)
    public String getStateId() {
        return this.stateId;
    }
    
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="CityId", length=16)
    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    
    @Column(name="ContactPersonZip", length=5)
    public String getContactPersonZip() {
        return this.contactPersonZip;
    }
    
    public void setContactPersonZip(String contactPersonZip) {
        this.contactPersonZip = contactPersonZip;
    }

    
    @Column(name="ContactWorkPhone", length=200)
    public String getContactWorkPhone() {
        return this.contactWorkPhone;
    }
    
    public void setContactWorkPhone(String contactWorkPhone) {
        this.contactWorkPhone = contactWorkPhone;
    }

    
    @Column(name="ContactHomePhone", length=200)
    public String getContactHomePhone() {
        return this.contactHomePhone;
    }
    
    public void setContactHomePhone(String contactHomePhone) {
        this.contactHomePhone = contactHomePhone;
    }

    
    @Column(name="ContactCellPhone", length=200)
    public String getContactCellPhone() {
        return this.contactCellPhone;
    }
    
    public void setContactCellPhone(String contactCellPhone) {
        this.contactCellPhone = contactCellPhone;
    }

    
    @Column(name="ContactPersonEmail", length=100)
    public String getContactPersonEmail() {
        return this.contactPersonEmail;
    }
    
    public void setContactPersonEmail(String contactPersonEmail) {
        this.contactPersonEmail = contactPersonEmail;
    }

    
    @Column(name="ContactPersonPass", length=200)
    public String getContactPersonPass() {
        return this.contactPersonPass;
    }
    
    public void setContactPersonPass(String contactPersonPass) {
        this.contactPersonPass = contactPersonPass;
    }

    
    @Column(name="IsLogin")
    public Boolean getIsLogin() {
        return this.isLogin;
    }
    
    public void setIsLogin(Boolean isLogin) {
        this.isLogin = isLogin;
    }

    
    @Column(name="IsDelete")
    public Boolean getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    
    @Column(name="IsConfirm")
    public Boolean getIsConfirm() {
        return this.isConfirm;
    }
    
    public void setIsConfirm(Boolean isConfirm) {
        this.isConfirm = isConfirm;
    }

    
    @Column(name="IsReset")
    public Boolean getIsReset() {
        return this.isReset;
    }
    
    public void setIsReset(Boolean isReset) {
        this.isReset = isReset;
    }

    
    @Column(name="ConfirmCode", length=200)
    public String getConfirmCode() {
        return this.confirmCode;
    }
    
    public void setConfirmCode(String confirmCode) {
        this.confirmCode = confirmCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastDateLogin", length=23)
    public Date getLastDateLogin() {
        return this.lastDateLogin;
    }
    
    public void setLastDateLogin(Date lastDateLogin) {
        this.lastDateLogin = lastDateLogin;
    }

    
    @Column(name="UserPrefix", length=3)
    public String getUserPrefix() {
        return this.userPrefix;
    }
    
    public void setUserPrefix(String userPrefix) {
        this.userPrefix = userPrefix;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


