package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SyCountry generated by hbm2java
 */
@Entity
@Table(name="SyCountry"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyCountry  implements java.io.Serializable {


     private String countryId;
     private String countryCode;
     private String countryName;
     private Boolean isExists;

    public SyCountry() {
    }

	
    public SyCountry(String countryId) {
        this.countryId = countryId;
    }
    public SyCountry(String countryId, String countryCode, String countryName, Boolean isExists) {
       this.countryId = countryId;
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.isExists = isExists;
    }
   
     @Id 

    
    @Column(name="CountryId", unique=true, nullable=false, length=6)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="CountryCode", length=3)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="CountryName", length=100)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }




}


