package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyGroupAccessModule generated by hbm2java
 */
@Entity
@Table(name="SyGroupAccessModule"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyGroupAccessModule  implements java.io.Serializable {


     private String groupAccessModuleId;
     private String groupAccessId;
     private String menuModuleId;
     private Date createdDate;
     private String createdBy;

    public SyGroupAccessModule() {
    }

	
    public SyGroupAccessModule(String groupAccessModuleId, String groupAccessId, String menuModuleId) {
        this.groupAccessModuleId = groupAccessModuleId;
        this.groupAccessId = groupAccessId;
        this.menuModuleId = menuModuleId;
    }
    public SyGroupAccessModule(String groupAccessModuleId, String groupAccessId, String menuModuleId, Date createdDate, String createdBy) {
       this.groupAccessModuleId = groupAccessModuleId;
       this.groupAccessId = groupAccessId;
       this.menuModuleId = menuModuleId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="GroupAccessModuleId", unique=true, nullable=false, length=36)
    public String getGroupAccessModuleId() {
        return this.groupAccessModuleId;
    }
    
    public void setGroupAccessModuleId(String groupAccessModuleId) {
        this.groupAccessModuleId = groupAccessModuleId;
    }

    
    @Column(name="GroupAccessId", nullable=false, length=40)
    public String getGroupAccessId() {
        return this.groupAccessId;
    }
    
    public void setGroupAccessId(String groupAccessId) {
        this.groupAccessId = groupAccessId;
    }

    
    @Column(name="MenuModuleId", nullable=false, length=10)
    public String getMenuModuleId() {
        return this.menuModuleId;
    }
    
    public void setMenuModuleId(String menuModuleId) {
        this.menuModuleId = menuModuleId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


