package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyGroupProductUsers generated by hbm2java
 */
@Entity
@Table(name="SyGroupProductUsers"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyGroupProductUsers  implements java.io.Serializable {


     private String groupProductUsersId;
     private String productsId;
     private String contactPersonId;
     private Date createdDate;
     private String createdBy;

    public SyGroupProductUsers() {
    }

	
    public SyGroupProductUsers(String groupProductUsersId, String productsId, String contactPersonId) {
        this.groupProductUsersId = groupProductUsersId;
        this.productsId = productsId;
        this.contactPersonId = contactPersonId;
    }
    public SyGroupProductUsers(String groupProductUsersId, String productsId, String contactPersonId, Date createdDate, String createdBy) {
       this.groupProductUsersId = groupProductUsersId;
       this.productsId = productsId;
       this.contactPersonId = contactPersonId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="GroupProductUsersId", unique=true, nullable=false, length=36)
    public String getGroupProductUsersId() {
        return this.groupProductUsersId;
    }
    
    public void setGroupProductUsersId(String groupProductUsersId) {
        this.groupProductUsersId = groupProductUsersId;
    }

    
    @Column(name="ProductsId", nullable=false, length=40)
    public String getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(String productsId) {
        this.productsId = productsId;
    }

    
    @Column(name="ContactPersonId", nullable=false, length=20)
    public String getContactPersonId() {
        return this.contactPersonId;
    }
    
    public void setContactPersonId(String contactPersonId) {
        this.contactPersonId = contactPersonId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


