package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyGroupAccessUsers generated by hbm2java
 */
@Entity
@Table(name="SyGroupAccessUsers"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyGroupAccessUsers  implements java.io.Serializable {


     private String groupAccessUsersId;
     private String groupAccessId;
     private String contactPersonId;
     private Date createdDate;
     private String createdBy;

    public SyGroupAccessUsers() {
    }

	
    public SyGroupAccessUsers(String groupAccessUsersId, String groupAccessId, String contactPersonId) {
        this.groupAccessUsersId = groupAccessUsersId;
        this.groupAccessId = groupAccessId;
        this.contactPersonId = contactPersonId;
    }
    public SyGroupAccessUsers(String groupAccessUsersId, String groupAccessId, String contactPersonId, Date createdDate, String createdBy) {
       this.groupAccessUsersId = groupAccessUsersId;
       this.groupAccessId = groupAccessId;
       this.contactPersonId = contactPersonId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="GroupAccessUsersId", unique=true, nullable=false, length=36)
    public String getGroupAccessUsersId() {
        return this.groupAccessUsersId;
    }
    
    public void setGroupAccessUsersId(String groupAccessUsersId) {
        this.groupAccessUsersId = groupAccessUsersId;
    }

    
    @Column(name="GroupAccessId", nullable=false, length=40)
    public String getGroupAccessId() {
        return this.groupAccessId;
    }
    
    public void setGroupAccessId(String groupAccessId) {
        this.groupAccessId = groupAccessId;
    }

    
    @Column(name="ContactPersonId", nullable=false, length=20)
    public String getContactPersonId() {
        return this.contactPersonId;
    }
    
    public void setContactPersonId(String contactPersonId) {
        this.contactPersonId = contactPersonId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


