package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyGroupAccess generated by hbm2java
 */
@Entity
@Table(name="SyGroupAccess"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyGroupAccess  implements java.io.Serializable {


     private String groupAccessId;
     private String groupAccessLabel;
     private String groupAccessDescription;
     private Boolean isActive;
     private Date createdDate;
     private String createdBy;
     private Date modifiedDate;
     private String modifiedBy;

    public SyGroupAccess() {
    }

	
    public SyGroupAccess(String groupAccessId) {
        this.groupAccessId = groupAccessId;
    }
    public SyGroupAccess(String groupAccessId, String groupAccessLabel, String groupAccessDescription, Boolean isActive, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
       this.groupAccessId = groupAccessId;
       this.groupAccessLabel = groupAccessLabel;
       this.groupAccessDescription = groupAccessDescription;
       this.isActive = isActive;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedDate = modifiedDate;
       this.modifiedBy = modifiedBy;
    }
   
     @Id 

    
    @Column(name="GroupAccessId", unique=true, nullable=false, length=40)
    public String getGroupAccessId() {
        return this.groupAccessId;
    }
    
    public void setGroupAccessId(String groupAccessId) {
        this.groupAccessId = groupAccessId;
    }

    
    @Column(name="GroupAccessLabel", length=40)
    public String getGroupAccessLabel() {
        return this.groupAccessLabel;
    }
    
    public void setGroupAccessLabel(String groupAccessLabel) {
        this.groupAccessLabel = groupAccessLabel;
    }

    
    @Column(name="GroupAccessDescription")
    public String getGroupAccessDescription() {
        return this.groupAccessDescription;
    }
    
    public void setGroupAccessDescription(String groupAccessDescription) {
        this.groupAccessDescription = groupAccessDescription;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


