package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SyLogError generated by hbm2java
 */
@Entity
@Table(name="SyLogError"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyLogError  implements java.io.Serializable {


     private int errorId;
     private String processType;
     private String processName;
     private String description;
     private Date createdDate;

    public SyLogError() {
    }

	
    public SyLogError(int errorId) {
        this.errorId = errorId;
    }
    public SyLogError(int errorId, String processType, String processName, String description, Date createdDate) {
       this.errorId = errorId;
       this.processType = processType;
       this.processName = processName;
       this.description = description;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="ErrorId", unique=true, nullable=false)
    public int getErrorId() {
        return this.errorId;
    }
    
    public void setErrorId(int errorId) {
        this.errorId = errorId;
    }

    
    @Column(name="ProcessType", length=50)
    public String getProcessType() {
        return this.processType;
    }
    
    public void setProcessType(String processType) {
        this.processType = processType;
    }

    
    @Column(name="ProcessName", length=100)
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }

    
    @Column(name="Description", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


