package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SyMenuModule generated by hbm2java
 */
@Entity
@Table(name="SyMenuModule"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyMenuModule  implements java.io.Serializable {


     private String menuModuleId;
     private SyMenuModule syMenuModule;
     private String menuCompanyId;
     private String menuGroup;
     private String menuLabel;
     private String menuDescription;
     private String menuUrl;
     private String menuUrlMvc;
     private Byte menuLevel;
     private Byte menuSortOrder;
     private Boolean menuIsVisible;
     private String menuRemark;
     private String menuFlagFolder;
     private String menuIcons;
     private Set syMenuModules = new HashSet(0);

    public SyMenuModule() {
    }

	
    public SyMenuModule(String menuModuleId) {
        this.menuModuleId = menuModuleId;
    }
    public SyMenuModule(String menuModuleId, SyMenuModule syMenuModule, String menuCompanyId, String menuGroup, String menuLabel, String menuDescription, String menuUrl, String menuUrlMvc, Byte menuLevel, Byte menuSortOrder, Boolean menuIsVisible, String menuRemark, String menuFlagFolder, String menuIcons, Set syMenuModules) {
       this.menuModuleId = menuModuleId;
       this.syMenuModule = syMenuModule;
       this.menuCompanyId = menuCompanyId;
       this.menuGroup = menuGroup;
       this.menuLabel = menuLabel;
       this.menuDescription = menuDescription;
       this.menuUrl = menuUrl;
       this.menuUrlMvc = menuUrlMvc;
       this.menuLevel = menuLevel;
       this.menuSortOrder = menuSortOrder;
       this.menuIsVisible = menuIsVisible;
       this.menuRemark = menuRemark;
       this.menuFlagFolder = menuFlagFolder;
       this.menuIcons = menuIcons;
       this.syMenuModules = syMenuModules;
    }
   
     @Id 

    
    @Column(name="MenuModuleId", unique=true, nullable=false, length=10)
    public String getMenuModuleId() {
        return this.menuModuleId;
    }
    
    public void setMenuModuleId(String menuModuleId) {
        this.menuModuleId = menuModuleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MenuParentId")
    public SyMenuModule getSyMenuModule() {
        return this.syMenuModule;
    }
    
    public void setSyMenuModule(SyMenuModule syMenuModule) {
        this.syMenuModule = syMenuModule;
    }

    
    @Column(name="MenuCompanyId", length=10)
    public String getMenuCompanyId() {
        return this.menuCompanyId;
    }
    
    public void setMenuCompanyId(String menuCompanyId) {
        this.menuCompanyId = menuCompanyId;
    }

    
    @Column(name="MenuGroup", length=40)
    public String getMenuGroup() {
        return this.menuGroup;
    }
    
    public void setMenuGroup(String menuGroup) {
        this.menuGroup = menuGroup;
    }

    
    @Column(name="MenuLabel", length=30)
    public String getMenuLabel() {
        return this.menuLabel;
    }
    
    public void setMenuLabel(String menuLabel) {
        this.menuLabel = menuLabel;
    }

    
    @Column(name="MenuDescription")
    public String getMenuDescription() {
        return this.menuDescription;
    }
    
    public void setMenuDescription(String menuDescription) {
        this.menuDescription = menuDescription;
    }

    
    @Column(name="MenuUrl")
    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    
    @Column(name="MenuUrlMvc")
    public String getMenuUrlMvc() {
        return this.menuUrlMvc;
    }
    
    public void setMenuUrlMvc(String menuUrlMvc) {
        this.menuUrlMvc = menuUrlMvc;
    }

    
    @Column(name="MenuLevel")
    public Byte getMenuLevel() {
        return this.menuLevel;
    }
    
    public void setMenuLevel(Byte menuLevel) {
        this.menuLevel = menuLevel;
    }

    
    @Column(name="MenuSortOrder")
    public Byte getMenuSortOrder() {
        return this.menuSortOrder;
    }
    
    public void setMenuSortOrder(Byte menuSortOrder) {
        this.menuSortOrder = menuSortOrder;
    }

    
    @Column(name="MenuIsVisible")
    public Boolean getMenuIsVisible() {
        return this.menuIsVisible;
    }
    
    public void setMenuIsVisible(Boolean menuIsVisible) {
        this.menuIsVisible = menuIsVisible;
    }

    
    @Column(name="MenuRemark", length=10)
    public String getMenuRemark() {
        return this.menuRemark;
    }
    
    public void setMenuRemark(String menuRemark) {
        this.menuRemark = menuRemark;
    }

    
    @Column(name="MenuFlagFolder", length=1)
    public String getMenuFlagFolder() {
        return this.menuFlagFolder;
    }
    
    public void setMenuFlagFolder(String menuFlagFolder) {
        this.menuFlagFolder = menuFlagFolder;
    }

    
    @Column(name="MenuIcons")
    public String getMenuIcons() {
        return this.menuIcons;
    }
    
    public void setMenuIcons(String menuIcons) {
        this.menuIcons = menuIcons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="syMenuModule")
    public Set getSyMenuModules() {
        return this.syMenuModules;
    }
    
    public void setSyMenuModules(Set syMenuModules) {
        this.syMenuModules = syMenuModules;
    }




}


