package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SyState generated by hbm2java
 */
@Entity
@Table(name="SyState"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class SyState  implements java.io.Serializable {


     private String stateId;
     private String countryId;
     private String stateName;
     private Boolean isExists;

    public SyState() {
    }

	
    public SyState(String stateId, String countryId) {
        this.stateId = stateId;
        this.countryId = countryId;
    }
    public SyState(String stateId, String countryId, String stateName, Boolean isExists) {
       this.stateId = stateId;
       this.countryId = countryId;
       this.stateName = stateName;
       this.isExists = isExists;
    }
   
     @Id 

    
    @Column(name="StateId", unique=true, nullable=false, length=10)
    public String getStateId() {
        return this.stateId;
    }
    
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="CountryId", nullable=false, length=6)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="StateName", length=100)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }




}


