package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmArea generated by hbm2java
 */
@Entity
@Table(name="TmArea"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmArea  implements java.io.Serializable {


     private String areaId;
     private TmRegion tmRegion;
     private String areaName;
     private Boolean isExists;
     private Integer createdBy;
     private Date createdDate;

    public TmArea() {
    }

	
    public TmArea(String areaId, TmRegion tmRegion) {
        this.areaId = areaId;
        this.tmRegion = tmRegion;
    }
    public TmArea(String areaId, TmRegion tmRegion, String areaName, Boolean isExists, Integer createdBy, Date createdDate) {
       this.areaId = areaId;
       this.tmRegion = tmRegion;
       this.areaName = areaName;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="AreaId", unique=true, nullable=false, length=20)
    public String getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RegionId", nullable=false)
    public TmRegion getTmRegion() {
        return this.tmRegion;
    }
    
    public void setTmRegion(TmRegion tmRegion) {
        this.tmRegion = tmRegion;
    }

    
    @Column(name="AreaName", length=100)
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CreatedDate", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


