package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmCompany generated by hbm2java
 */
@Entity
@Table(name="TmCompany"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmCompany  implements java.io.Serializable {


     private String compId;
     private String compName;
     private String compAddress;
     private String compPostCode;
     private String compCity;
     private String compCountry;
     private String compPhone;
     private String compFax;
     private String compEmail;
     private String npwp;
     private String compFlag;
     private Boolean isExists;
     private Integer createdBy;
     private Date createdDate;
     private Set tmContacts = new HashSet(0);

    public TmCompany() {
    }

	
    public TmCompany(String compId) {
        this.compId = compId;
    }
    public TmCompany(String compId, String compName, String compAddress, String compPostCode, String compCity, String compCountry, String compPhone, String compFax, String compEmail, String npwp, String compFlag, Boolean isExists, Integer createdBy, Date createdDate, Set tmContacts) {
       this.compId = compId;
       this.compName = compName;
       this.compAddress = compAddress;
       this.compPostCode = compPostCode;
       this.compCity = compCity;
       this.compCountry = compCountry;
       this.compPhone = compPhone;
       this.compFax = compFax;
       this.compEmail = compEmail;
       this.npwp = npwp;
       this.compFlag = compFlag;
       this.isExists = isExists;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.tmContacts = tmContacts;
    }
   
     @Id 

    
    @Column(name="CompId", unique=true, nullable=false, length=40)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    
    @Column(name="CompName", length=250)
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }

    
    @Column(name="CompAddress", length=250)
    public String getCompAddress() {
        return this.compAddress;
    }
    
    public void setCompAddress(String compAddress) {
        this.compAddress = compAddress;
    }

    
    @Column(name="CompPostCode", length=5)
    public String getCompPostCode() {
        return this.compPostCode;
    }
    
    public void setCompPostCode(String compPostCode) {
        this.compPostCode = compPostCode;
    }

    
    @Column(name="CompCity", length=100)
    public String getCompCity() {
        return this.compCity;
    }
    
    public void setCompCity(String compCity) {
        this.compCity = compCity;
    }

    
    @Column(name="CompCountry", length=100)
    public String getCompCountry() {
        return this.compCountry;
    }
    
    public void setCompCountry(String compCountry) {
        this.compCountry = compCountry;
    }

    
    @Column(name="CompPhone", length=40)
    public String getCompPhone() {
        return this.compPhone;
    }
    
    public void setCompPhone(String compPhone) {
        this.compPhone = compPhone;
    }

    
    @Column(name="CompFax", length=40)
    public String getCompFax() {
        return this.compFax;
    }
    
    public void setCompFax(String compFax) {
        this.compFax = compFax;
    }

    
    @Column(name="CompEmail", length=40)
    public String getCompEmail() {
        return this.compEmail;
    }
    
    public void setCompEmail(String compEmail) {
        this.compEmail = compEmail;
    }

    
    @Column(name="NPWP", length=50)
    public String getNpwp() {
        return this.npwp;
    }
    
    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }

    
    @Column(name="CompFlag", length=10)
    public String getCompFlag() {
        return this.compFlag;
    }
    
    public void setCompFlag(String compFlag) {
        this.compFlag = compFlag;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tmCompany")
    public Set getTmContacts() {
        return this.tmContacts;
    }
    
    public void setTmContacts(Set tmContacts) {
        this.tmContacts = tmContacts;
    }




}


