package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TmContact generated by hbm2java
 */
@Entity
@Table(name="TmContact"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmContact  implements java.io.Serializable {


     private String contactId;
     private TmCompany tmCompany;
     private String contactName;
     private String contactPhone;
     private String contactMobile;
     private String contactEmail;
     private Boolean isExists;

    public TmContact() {
    }

	
    public TmContact(String contactId, TmCompany tmCompany) {
        this.contactId = contactId;
        this.tmCompany = tmCompany;
    }
    public TmContact(String contactId, TmCompany tmCompany, String contactName, String contactPhone, String contactMobile, String contactEmail, Boolean isExists) {
       this.contactId = contactId;
       this.tmCompany = tmCompany;
       this.contactName = contactName;
       this.contactPhone = contactPhone;
       this.contactMobile = contactMobile;
       this.contactEmail = contactEmail;
       this.isExists = isExists;
    }
   
     @Id 

    
    @Column(name="ContactId", unique=true, nullable=false, length=40)
    public String getContactId() {
        return this.contactId;
    }
    
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CompId", nullable=false)
    public TmCompany getTmCompany() {
        return this.tmCompany;
    }
    
    public void setTmCompany(TmCompany tmCompany) {
        this.tmCompany = tmCompany;
    }

    
    @Column(name="ContactName", length=100)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    
    @Column(name="ContactPhone", length=40)
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    
    @Column(name="ContactMobile", length=40)
    public String getContactMobile() {
        return this.contactMobile;
    }
    
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    
    @Column(name="ContactEmail", length=40)
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }




}


