package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TmDropDownList generated by hbm2java
 */
@Entity
@Table(name="TmDropDownList"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmDropDownList  implements java.io.Serializable {


     private String dropDownListId;
     private String dropDownListName;
     private String dropDownListGroup;
     private String productId;

    public TmDropDownList() {
    }

	
    public TmDropDownList(String dropDownListId) {
        this.dropDownListId = dropDownListId;
    }
    public TmDropDownList(String dropDownListId, String dropDownListName, String dropDownListGroup, String productId) {
       this.dropDownListId = dropDownListId;
       this.dropDownListName = dropDownListName;
       this.dropDownListGroup = dropDownListGroup;
       this.productId = productId;
    }
   
     @Id 

    
    @Column(name="DropDownListId", unique=true, nullable=false, length=40)
    public String getDropDownListId() {
        return this.dropDownListId;
    }
    
    public void setDropDownListId(String dropDownListId) {
        this.dropDownListId = dropDownListId;
    }

    
    @Column(name="DropDownListName", length=40)
    public String getDropDownListName() {
        return this.dropDownListName;
    }
    
    public void setDropDownListName(String dropDownListName) {
        this.dropDownListName = dropDownListName;
    }

    
    @Column(name="DropDownListGroup", length=100)
    public String getDropDownListGroup() {
        return this.dropDownListGroup;
    }
    
    public void setDropDownListGroup(String dropDownListGroup) {
        this.dropDownListGroup = dropDownListGroup;
    }

    
    @Column(name="ProductId", length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }




}


