package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmGroup generated by hbm2java
 */
@Entity
@Table(name="TmGroup"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmGroup  implements java.io.Serializable {


     private String idGroup;
     private String groupName;
     private Double existence;
     private Date createdDate;
     private Double createdBy;
     private Date modifiedDate;
     private Double modifiedBy;

    public TmGroup() {
    }

	
    public TmGroup(String idGroup) {
        this.idGroup = idGroup;
    }
    public TmGroup(String idGroup, String groupName, Double existence, Date createdDate, Double createdBy, Date modifiedDate, Double modifiedBy) {
       this.idGroup = idGroup;
       this.groupName = groupName;
       this.existence = existence;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedDate = modifiedDate;
       this.modifiedBy = modifiedBy;
    }
   
     @Id 

    
    @Column(name="id_group", unique=true, nullable=false, length=5)
    public String getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(String idGroup) {
        this.idGroup = idGroup;
    }

    
    @Column(name="group_name", length=100)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    @Column(name="existence", precision=53, scale=0)
    public Double getExistence() {
        return this.existence;
    }
    
    public void setExistence(Double existence) {
        this.existence = existence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by", precision=53, scale=0)
    public Double getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Double createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="modified_by", precision=53, scale=0)
    public Double getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Double modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


