package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TmpCheckMaterial generated by hbm2java
 */
@Entity
@Table(name="_TmpCheckMaterial"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmpCheckMaterial  implements java.io.Serializable {


     private Serializable materialSerialNumber;
     private String materialGroupId;
     private String materialTypeId;
     private Boolean isRecieved;

    public TmpCheckMaterial() {
    }

	
    public TmpCheckMaterial(Serializable materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }
    public TmpCheckMaterial(Serializable materialSerialNumber, String materialGroupId, String materialTypeId, Boolean isRecieved) {
       this.materialSerialNumber = materialSerialNumber;
       this.materialGroupId = materialGroupId;
       this.materialTypeId = materialTypeId;
       this.isRecieved = isRecieved;
    }
   
     @Id 

    
    @Column(name="MaterialSerialNumber", unique=true, nullable=false)
    public Serializable getMaterialSerialNumber() {
        return this.materialSerialNumber;
    }
    
    public void setMaterialSerialNumber(Serializable materialSerialNumber) {
        this.materialSerialNumber = materialSerialNumber;
    }

    
    @Column(name="MaterialGroupId", length=40)
    public String getMaterialGroupId() {
        return this.materialGroupId;
    }
    
    public void setMaterialGroupId(String materialGroupId) {
        this.materialGroupId = materialGroupId;
    }

    
    @Column(name="MaterialTypeId", length=40)
    public String getMaterialTypeId() {
        return this.materialTypeId;
    }
    
    public void setMaterialTypeId(String materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    
    @Column(name="IsRecieved")
    public Boolean getIsRecieved() {
        return this.isRecieved;
    }
    
    public void setIsRecieved(Boolean isRecieved) {
        this.isRecieved = isRecieved;
    }




}


