package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmProductUsers generated by hbm2java
 */
@Entity
@Table(name="TmProductUsers"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmProductUsers  implements java.io.Serializable {


     private String productUsersId;
     private int userid;
     private String productId;
     private String groupId;
     private Boolean isExists;
     private Boolean isActive;
     private Date createdDate;
     private Integer createdBy;

    public TmProductUsers() {
    }

	
    public TmProductUsers(String productUsersId, int userid, String productId) {
        this.productUsersId = productUsersId;
        this.userid = userid;
        this.productId = productId;
    }
    public TmProductUsers(String productUsersId, int userid, String productId, String groupId, Boolean isExists, Boolean isActive, Date createdDate, Integer createdBy) {
       this.productUsersId = productUsersId;
       this.userid = userid;
       this.productId = productId;
       this.groupId = groupId;
       this.isExists = isExists;
       this.isActive = isActive;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="ProductUsersId", unique=true, nullable=false, length=36)
    public String getProductUsersId() {
        return this.productUsersId;
    }
    
    public void setProductUsersId(String productUsersId) {
        this.productUsersId = productUsersId;
    }

    
    @Column(name="userid", nullable=false)
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

    
    @Column(name="ProductId", nullable=false, length=40)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="GroupId", length=5)
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


