package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmWidgetPrivateMessage generated by hbm2java
 */
@Entity
@Table(name="TmWidgetPrivateMessage"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TmWidgetPrivateMessage  implements java.io.Serializable {


     private String widgetPrivateMessageId;
     private Integer userId;
     private String groupId;
     private String widgetHeader;
     private String widgetContent;
     private String signatureBy;
     private Date openDate;
     private Date closeDate;
     private Boolean isPersonal;
     private Boolean isActive;
     private Integer createdBy;
     private Date createdDate;

    public TmWidgetPrivateMessage() {
    }

	
    public TmWidgetPrivateMessage(String widgetPrivateMessageId) {
        this.widgetPrivateMessageId = widgetPrivateMessageId;
    }
    public TmWidgetPrivateMessage(String widgetPrivateMessageId, Integer userId, String groupId, String widgetHeader, String widgetContent, String signatureBy, Date openDate, Date closeDate, Boolean isPersonal, Boolean isActive, Integer createdBy, Date createdDate) {
       this.widgetPrivateMessageId = widgetPrivateMessageId;
       this.userId = userId;
       this.groupId = groupId;
       this.widgetHeader = widgetHeader;
       this.widgetContent = widgetContent;
       this.signatureBy = signatureBy;
       this.openDate = openDate;
       this.closeDate = closeDate;
       this.isPersonal = isPersonal;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="WidgetPrivateMessageId", unique=true, nullable=false, length=36)
    public String getWidgetPrivateMessageId() {
        return this.widgetPrivateMessageId;
    }
    
    public void setWidgetPrivateMessageId(String widgetPrivateMessageId) {
        this.widgetPrivateMessageId = widgetPrivateMessageId;
    }

    
    @Column(name="UserId")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="GroupId", length=5)
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="WidgetHeader", length=100)
    public String getWidgetHeader() {
        return this.widgetHeader;
    }
    
    public void setWidgetHeader(String widgetHeader) {
        this.widgetHeader = widgetHeader;
    }

    
    @Column(name="WidgetContent", length=250)
    public String getWidgetContent() {
        return this.widgetContent;
    }
    
    public void setWidgetContent(String widgetContent) {
        this.widgetContent = widgetContent;
    }

    
    @Column(name="SignatureBy", length=250)
    public String getSignatureBy() {
        return this.signatureBy;
    }
    
    public void setSignatureBy(String signatureBy) {
        this.signatureBy = signatureBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OpenDate", length=23)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CloseDate", length=23)
    public Date getCloseDate() {
        return this.closeDate;
    }
    
    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }

    
    @Column(name="IsPersonal")
    public Boolean getIsPersonal() {
        return this.isPersonal;
    }
    
    public void setIsPersonal(Boolean isPersonal) {
        this.isPersonal = isPersonal;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="CreatedBy")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


