package entities;
// Generated Nov 4, 2017 6:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionHeader generated by hbm2java
 */
@Entity
@Table(name="TransactionHeader"
    ,schema="dbo"
    ,catalog="ProjectManagement"
)
public class TransactionHeader  implements java.io.Serializable {


     private String mainFormId;
     private String mainFormType;
     private String parentFormId;
     private String parentFormType;
     private String projectSupportId;
     private String subjectId;
     private String refDocument;
     private Date refDocumentDate;
     private Date transDate;
     private Date etadate;
     private String sendFrom;
     private String sendTo;
     private String reason;
     private String note;
     private String transportationMode;
     private String idComplation;
     private Boolean isClosed;
     private Boolean isExists;
     private Boolean isSubmit;
     private String remark;
     private Date submitDate;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set loDeliveryOrderSiteIds = new HashSet(0);
     private Set loDeliveryRequests = new HashSet(0);
     private Set loDeliveryOrders = new HashSet(0);
     private Set loDeliveryRequestSiteIds = new HashSet(0);
     private Set ptSiteProgresses = new HashSet(0);
     private Set loDeliveryNotes = new HashSet(0);
     private Set oldTransactionDetails = new HashSet(0);

    public TransactionHeader() {
    }

	
    public TransactionHeader(String mainFormId) {
        this.mainFormId = mainFormId;
    }
    public TransactionHeader(String mainFormId, String mainFormType, String parentFormId, String parentFormType, String projectSupportId, String subjectId, String refDocument, Date refDocumentDate, Date transDate, Date etadate, String sendFrom, String sendTo, String reason, String note, String transportationMode, String idComplation, Boolean isClosed, Boolean isExists, Boolean isSubmit, String remark, Date submitDate, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, Set loDeliveryOrderSiteIds, Set loDeliveryRequests, Set loDeliveryOrders, Set loDeliveryRequestSiteIds, Set ptSiteProgresses, Set loDeliveryNotes, Set oldTransactionDetails) {
       this.mainFormId = mainFormId;
       this.mainFormType = mainFormType;
       this.parentFormId = parentFormId;
       this.parentFormType = parentFormType;
       this.projectSupportId = projectSupportId;
       this.subjectId = subjectId;
       this.refDocument = refDocument;
       this.refDocumentDate = refDocumentDate;
       this.transDate = transDate;
       this.etadate = etadate;
       this.sendFrom = sendFrom;
       this.sendTo = sendTo;
       this.reason = reason;
       this.note = note;
       this.transportationMode = transportationMode;
       this.idComplation = idComplation;
       this.isClosed = isClosed;
       this.isExists = isExists;
       this.isSubmit = isSubmit;
       this.remark = remark;
       this.submitDate = submitDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.loDeliveryOrderSiteIds = loDeliveryOrderSiteIds;
       this.loDeliveryRequests = loDeliveryRequests;
       this.loDeliveryOrders = loDeliveryOrders;
       this.loDeliveryRequestSiteIds = loDeliveryRequestSiteIds;
       this.ptSiteProgresses = ptSiteProgresses;
       this.loDeliveryNotes = loDeliveryNotes;
       this.oldTransactionDetails = oldTransactionDetails;
    }
   
     @Id 

    
    @Column(name="MainFormId", unique=true, nullable=false, length=40)
    public String getMainFormId() {
        return this.mainFormId;
    }
    
    public void setMainFormId(String mainFormId) {
        this.mainFormId = mainFormId;
    }

    
    @Column(name="MainFormType", length=100)
    public String getMainFormType() {
        return this.mainFormType;
    }
    
    public void setMainFormType(String mainFormType) {
        this.mainFormType = mainFormType;
    }

    
    @Column(name="ParentFormId", length=40)
    public String getParentFormId() {
        return this.parentFormId;
    }
    
    public void setParentFormId(String parentFormId) {
        this.parentFormId = parentFormId;
    }

    
    @Column(name="ParentFormType", length=100)
    public String getParentFormType() {
        return this.parentFormType;
    }
    
    public void setParentFormType(String parentFormType) {
        this.parentFormType = parentFormType;
    }

    
    @Column(name="ProjectSupportId", length=50)
    public String getProjectSupportId() {
        return this.projectSupportId;
    }
    
    public void setProjectSupportId(String projectSupportId) {
        this.projectSupportId = projectSupportId;
    }

    
    @Column(name="SubjectId", length=40)
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="RefDocument", length=100)
    public String getRefDocument() {
        return this.refDocument;
    }
    
    public void setRefDocument(String refDocument) {
        this.refDocument = refDocument;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RefDocumentDate", length=23)
    public Date getRefDocumentDate() {
        return this.refDocumentDate;
    }
    
    public void setRefDocumentDate(Date refDocumentDate) {
        this.refDocumentDate = refDocumentDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransDate", length=23)
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ETADate", length=23)
    public Date getEtadate() {
        return this.etadate;
    }
    
    public void setEtadate(Date etadate) {
        this.etadate = etadate;
    }

    
    @Column(name="SendFrom", length=40)
    public String getSendFrom() {
        return this.sendFrom;
    }
    
    public void setSendFrom(String sendFrom) {
        this.sendFrom = sendFrom;
    }

    
    @Column(name="SendTo", length=40)
    public String getSendTo() {
        return this.sendTo;
    }
    
    public void setSendTo(String sendTo) {
        this.sendTo = sendTo;
    }

    
    @Column(name="Reason", length=250)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="Note", length=250)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="TransportationMode", length=40)
    public String getTransportationMode() {
        return this.transportationMode;
    }
    
    public void setTransportationMode(String transportationMode) {
        this.transportationMode = transportationMode;
    }

    
    @Column(name="IdComplation", length=40)
    public String getIdComplation() {
        return this.idComplation;
    }
    
    public void setIdComplation(String idComplation) {
        this.idComplation = idComplation;
    }

    
    @Column(name="IsClosed")
    public Boolean getIsClosed() {
        return this.isClosed;
    }
    
    public void setIsClosed(Boolean isClosed) {
        this.isClosed = isClosed;
    }

    
    @Column(name="IsExists")
    public Boolean getIsExists() {
        return this.isExists;
    }
    
    public void setIsExists(Boolean isExists) {
        this.isExists = isExists;
    }

    
    @Column(name="IsSubmit")
    public Boolean getIsSubmit() {
        return this.isSubmit;
    }
    
    public void setIsSubmit(Boolean isSubmit) {
        this.isSubmit = isSubmit;
    }

    
    @Column(name="Remark", length=40)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SubmitDate", length=23)
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    
    @Column(name="CreatedBy", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="ModifiedBy", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifiedDate", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getLoDeliveryOrderSiteIds() {
        return this.loDeliveryOrderSiteIds;
    }
    
    public void setLoDeliveryOrderSiteIds(Set loDeliveryOrderSiteIds) {
        this.loDeliveryOrderSiteIds = loDeliveryOrderSiteIds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getLoDeliveryRequests() {
        return this.loDeliveryRequests;
    }
    
    public void setLoDeliveryRequests(Set loDeliveryRequests) {
        this.loDeliveryRequests = loDeliveryRequests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getLoDeliveryOrders() {
        return this.loDeliveryOrders;
    }
    
    public void setLoDeliveryOrders(Set loDeliveryOrders) {
        this.loDeliveryOrders = loDeliveryOrders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getLoDeliveryRequestSiteIds() {
        return this.loDeliveryRequestSiteIds;
    }
    
    public void setLoDeliveryRequestSiteIds(Set loDeliveryRequestSiteIds) {
        this.loDeliveryRequestSiteIds = loDeliveryRequestSiteIds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getPtSiteProgresses() {
        return this.ptSiteProgresses;
    }
    
    public void setPtSiteProgresses(Set ptSiteProgresses) {
        this.ptSiteProgresses = ptSiteProgresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getLoDeliveryNotes() {
        return this.loDeliveryNotes;
    }
    
    public void setLoDeliveryNotes(Set loDeliveryNotes) {
        this.loDeliveryNotes = loDeliveryNotes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionHeader")
    public Set getOldTransactionDetails() {
        return this.oldTransactionDetails;
    }
    
    public void setOldTransactionDetails(Set oldTransactionDetails) {
        this.oldTransactionDetails = oldTransactionDetails;
    }




}


